### ISSUE TITLE
Could not download archive via api v3 since 8.3.2 CE

### ISSUE THREAD

**Issue by tritumRz** [gitlabhq/gitlabhq#9946] opened 2016-01-04 22:01 UTC
After updating to 8.3.2 CE (from 8.3.1 CE via omnibus package) a api call like

    curl --header "PRIVATE-TOKEN: xxx" "https://code.example.com/api/v3/projects/some_namespace%2Fsome_reponame/repository/archive.zip"   

results in a json response like

    {
        "RepoPath":"/var/opt/gitlab/git-data/repositories/some_namespace/some_reponame.git",
        "ArchivePrefix":"some_reponame-master-ee753b221e500f0d83e3ab422887339c6258df4a",
        "ArchivePath":"/var/opt/gitlab/gitlab-rails/shared/cache/archive/some_reponame.git/some_reponame-master-ee753b221e500f0d83e3ab422887339c6258df4a.zip",
        "CommitId":"ee753b221e500f0d83e3ab422887339c6258df4a"
    }

With Version 8.3.1 CE such a call returned the zip data (as expected).
I tested the same call with another installation (version 8.0.5 CE) and i got the zip data (as expected).
After updating this installation to 8.3.2 CE i got the json response (like above).
The archive path `/var/opt/gitlab/gitlab-rails/shared/cache/archive/some_reponame.git/` stay empty.
The documentation shows no changes in the API call.
Can someone reproduce my issue?

Thank you.

**Comment by stanhu** [comment] 2016-01-05 02:26
Yes, this is a duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/4124 and a [fix is in the works](https://gitlab.com/gitlab-org/gitlab-workhorse/merge_requests/23). Slated for 8.3.3.

**Closed by stanhu** 2016-01-05 02:26 UTC

**Comment by thiaguerd** [comment] 2016-01-12 14:40
i am using 8.3.3 and it is not solved :(

**Comment by stanhu** [comment] 2016-01-12 15:41
Are you using the 8.3.3-ce.1 release? It should look like this:

```
$ dpkg -l | grep gitlab-ce
ii  gitlab-ce                             8.3.3-ce.1                           amd64        GitLab Community Edition and GitLab CI (including NGINX, Postgres, Redis)
```

**Comment by thiaguerd** [comment] 2016-01-13 14:23
yeah, i am using 8.3.3-ce.1

**Comment by tritumRz** [comment] 2016-01-13 14:44
It works with 8.3.4

**Comment by thiaguerd** [comment] 2016-01-13 15:27
how update to 8.3.4?

**Comment by thiaguerd** [comment] 2016-01-13 18:31
sorry. I had not seen the version 8.3.4 was released, i am installing now

**Comment by thiaguerd** [comment] 2016-01-13 19:03
8.3.4-ce.0 not solve this :(
