### ISSUE TITLE
GitLab 7.11.2  500 on submitting a merge request

### ISSUE THREAD

**Issue by itxx00** [gitlabhq/gitlabhq#9333] opened 2015-05-27 09:29 UTC
Same error with https://gitlab.com/gitlab-org/gitlab-ce/issues/1650, error log:
```
NoMethodError (undefined method `primary_key' for ExternalIssue:Class):
  app/services/system_note_service.rb:210:in `create_note'
  app/services/system_note_service.rb:167:in `cross_reference'
  app/models/note.rb:68:in `create_cross_reference_note'
  app/models/concerns/mentionable.rb:67:in `block in create_cross_references!'
  app/models/concerns/mentionable.rb:66:in `each'
  app/models/concerns/mentionable.rb:66:in `create_cross_references!'
  app/services/merge_requests/create_service.rb:14:in `execute'
  app/controllers/projects/merge_requests_controller.rb:89:in `create'
```

**Comment by stefan-it** [comment] 2015-05-28 08:25
This bug was fixed in 7a2fd816f01c8723e61563789413ea1951d79668 and it included in *7.11.3* :)

Thanks for fixing!

**Comment by itxx00** [comment] 2015-05-29 01:33
After upgraded to 7.11.3,  everything works in order now, thanks.

**Comment by itxx00** [comment] 2015-05-29 03:48
after more tests,  some repos are ok while there is still one repo didn't work, so sad..:-(

**Comment by stefan-it** [comment] 2015-05-29 08:23
@itxx00 Could you please post a Merge Request description where you got the 500 message?

**Comment by itxx00** [comment] 2015-05-29 09:19
@stefan-it   I upgraded GitLab to 7.11.4, when I push a new branch , the activity page does not show this event,but the branch is successful pushed. and I create merge request in the normal steps,
,  after click 'submit a new merge request' button,  500 error page jumps out. 
This repo enabled Redmine service as an issue tracker,  when create a merge request, the default title generated by gitlab is in this form '#3000: drop support for libvirt storage pool',   if the title starts with '#3000'  , then 500 error will happen.

**Comment by stefan-it** [comment] 2015-05-29 09:32
With *7.11.4* and using the "internal" issue tracker I can create MR with starting issue references with no error messages. So I guees it has something to do with an external issue tracking system.

**Comment by ross-w** [comment] 2015-06-01 05:22
We are also having this isue on 7.11.4, unable to load any MR with ticket references:
```
NoMethodError (undefined method `uniq' for nil:NilClass):
  lib/gitlab/reference_extractor.rb:32:in `issues'
  lib/gitlab/closing_issue_extractor.rb:17:in `closed_by_message'
  app/models/commit.rb:126:in `closes_issues'
  app/models/merge_request.rb:286:in `block in closes_issues'
  app/models/merge_request.rb:286:in `each'
  app/models/merge_request.rb:286:in `flat_map'
  app/models/merge_request.rb:286:in `closes_issues'
  app/controllers/projects/merge_requests_controller.rb:198:in `closes_issues'
```

**Comment by rob19780114** [comment] 2015-06-09 08:40
Getting this error in 7.11.4 as well:

```
NoMethodError (undefined method `primary_key' for ExternalIssue:Class):
app/services/system_note_service.rb:210:in `create_note'
app/services/system_note_service.rb:167:in `cross_reference'
app/models/note.rb:68:in `create_cross_reference_note'
app/models/concerns/mentionable.rb:67:in `block in create_cross_references!'
app/models/concerns/mentionable.rb:66:in `each'
app/models/concerns/mentionable.rb:66:in `create_cross_references!'
app/services/merge_requests/create_service.rb:14:in `execute'
app/controllers/projects/merge_requests_controller.rb:89:in `create'```

**Comment by stanhu** [comment] 2015-06-09 17:42
I think there is a proposed fix for this error here:

https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/766

**Comment by rob19780114** [comment] 2015-06-10 07:33
Worked, thank you.

**Comment by dgerhardt** [comment] 2015-06-10 20:55
In [!766](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/766) I have only addressed the issue for push events. Are you sure that the issue is gone now? I have now created [!794](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/794) which addresses the bug with references to external issues in merge requests.

**Comment by itxx00** [comment] 2015-06-11 01:12
@dgerhardt :+1:   !794 and !766 fixed my issue,  nice :-P !

**Comment by rob19780114** [comment] 2015-06-11 06:29
@dgerhardt Adding !766 to my checkout fixed it "for me". I added !766 to be sure, that nothing will fire back on me. :)

**Comment by rob19780114** [comment] 2015-06-12 07:18
@dgerhardt Sorry, I have to revoke my comment. The error returned and it's completly reproducable.

**Comment by stanhu** [comment] 2015-07-17 05:42
Should be fixed in GitLab v7.13 due out on July 22.

**Closed by stanhu** 2015-07-17 05:42 UTC
