### ISSUE TITLE
Gitlab CE Tags triggering builds

### ISSUE THREAD

**Issue by Sladewill** [gitlabhq/gitlabhq#9945] opened 2016-01-04 10:56 UTC
On version 8.3.2 gitlab CE when you create a tag on the `web UI` it does not trigger a build to gitlab ci this was working on the previous versions but it appears the recent update to the latest has this issue.

It does however work from a external interface such as sourcetree.

**Comment by atomaka** [comment] 2016-01-06 15:55
I can confirm this issue.  Creating a tag via the web interface does not trigger a build.  However, if I create a local tag and then push to the remote, the build will run as expect.  The following is my `.gitlab-ci.yml file`

```
build:
  script:
    - docker build -t atomaka/link-share .
  except:
    - tags
deploy:
  script:
    - VERSION=$(git describe --tags)
    - docker build -t atomaka/link-share .
    - docker tag atomaka/link-share:latest example.com/atomaka/link-share:$VERSION
    - docker tag atomaka/link-share:latest example.com/atomaka/link-share:latest
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD -e me@example.com example.com
    - docker push example.com/atomaka/link-share
  only:
    - tags
```

This build file functioned as expected prior to upgrading so we are looking at a regression.

**Comment by doenietzomoeilijk** [comment] 2016-01-08 09:49
I may have a related problem. We don't use tags but rather branches, but we also see (after upgrading to 8.3.2) pushes not resulting in a build. Pushing again (after adding a newline to a readme or something silly like that) usually gets the build going. I haven't been able to reliably reproduce the behaviour, however, I did notice this in the sidekiq.log:

```
2016-01-05T16:01:17.323Z 12374 TID-12myns WARN: {"class"=>"PostReceive", "args"=>["/gitlab/repositories/XXX/YYY.git", "key-ZZZ", "STUFF\n"]}
2016-01-05T16:01:17.323Z 12374 TID-12myns WARN: Errno::ECONNREFUSED: Connection refused - connect(2) for nil port 80
2016-01-05T16:01:17.323Z 12374 TID-12myns WARN: /opt/gitlab/embedded/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
```

...followed by a lengthy trace that's probably not needed here. This error pops up every time someone has a non-triggering push, so it seems the two are related.

Env info:

```
System information
System:     Ubuntu 14.04
Current User:   git
Using RVM:  no
Ruby Version:   2.1.7p400
Gem Version:    2.5.1
Bundler Version:1.10.6
Rake Version:   10.4.2
Sidekiq Version:4.0.1

GitLab information
Version:    8.3.2
Revision:   fbb8b6e
Directory:  /opt/gitlab/embedded/service/gitlab-rails
DB Adapter: postgresql
URL:        http://gitlab.vdlp.nl
HTTP Clone URL: http://gitlab.vdlp.nl/some-group/some-project.git
SSH Clone URL:  git@gitlab.vdlp.nl:some-group/some-project.git
Using LDAP: no
Using Omniauth: no

GitLab Shell
Version:    2.6.9
Repositories:   /gitlab/repositories
Hooks:      /opt/gitlab/embedded/service/gitlab-shell/hooks/
Git:        /opt/gitlab/embedded/bin/git
```

Running gitlab:check shows green across the board.

I haven't tried triggering a push from the web UI, yet. Meanwhile, would it be possible for @Sladewill and @atomaka to grep their `/var/log/gitlab/gitlab-rails/sidekiq.log` for to see if they get that same error? If not, I might be running into a different issue for which I'd have to open a separate issue.

**Comment by maclof** [comment] 2016-01-08 15:58
@doenietzomoeilijk I've spoken with @Sladewill (my colleague) and we looked through both production.log and sidekick.log and couldn't any error like you described.

**Comment by doenietzomoeilijk** [comment] 2016-01-11 10:53
@maclof OK, that means I'm running into a different issue, then, I'll open a separate Issue for it. Thanks!

**Comment by Razer6** [comment] 2016-01-11 15:08
Clsoing as a duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/4296 and pedning fix in https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/2366

**Closed by Razer6** 2016-01-11 15:08 UTC
