### ISSUE TITLE
custom_hooks no more working

### ISSUE THREAD

**Issue by Poil** [gitlabhq/gitlabhq#8842] opened 2015-02-23 09:58 UTC
Hi,

With 7.8 custom_hooks doesn't seem to work anymore, I have no error in logs.

Best regards

**Comment by Razer6** [comment] 2015-02-23 10:00
Duplicate of https://gitlab.com/gitlab-org/omnibus-gitlab/issues/438

**Closed by Razer6** 2015-02-23 10:00 UTC
Labels: Confirmed issue
