### ISSUE TITLE
Openssh 6.8 fingerprint error

### ISSUE THREAD

**Issue by Araeos** [gitlabhq/gitlabhq#9016] opened 2015-03-24 20:03 UTC
# Descriptions

## Summary

Adding a public key using the web interface fails, unable to generate a fingerprint.

## Details

Adding a correctly formatted openssh public key fails with the red error text similiar to issue #7413.
The key is correctly formatted and using the rails console with the command

> Gitlab::Popen.popen(%W(ssh-keygen -lf /tmp/mykey.pub), '/tmp')

yields

> => ["2048 SHA256:g46P/hZKy/teaxfzjmyumd3KFwTWlfq2VJ8zgD5QxwU felix@caeros (RSA)\n", 0]

showing the successfully generated fingerprint in the new format described in the changelog:

>  * Add FingerprintHash option to ssh(1) and sshd(8), and equivalent
>   command-line flags to the other tools to control algorithm used
>   for key fingerprints. The default changes from MD5 to SHA256 and
>   format from hex to base64.
>
>   Fingerprints now have the hash algorithm prepended. An example of
>   the new format: SHA256:mVPwvezndPv/ARoIadVY98vAC0g+P/5633yTC4d/wXE
>   Please note that visual host keys will also be differen

## Workaround

Downgrade to openssh 6.7 works.

## Additional Info

gitlab: 7.9.0
gitlab-shell: 2.6.0
Openssh: 6.8
OS: Archlinux
selinux is not installed

**Comment by stanhu** [comment] 2015-03-25 07:15
Thanks--it looks like this is a duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/1289 and a fix is being reviewed here: https://github.com/gitlabhq/gitlabhq/pull/9008.

**Comment by muraiki** [comment] 2015-04-08 17:13
Hi, is there any ETA on this? It seems I'm having the same problem on Ubuntu 12.04.

**Comment by Razer6** [comment] 2015-09-04 16:11
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Closed by Razer6** 2015-09-04 16:11 UTC
