### ISSUE TITLE
6.0 -> 7.3  undefined method `shift' for #<Issue::ActiveRecord_Relation  

### ISSUE THREAD

**Issue by allan-simon** [gitlabhq/gitlabhq#7869] opened 2014-09-26 17:05 UTC
Hello I'm upgrading my version 6.0 version to the version 7.3  has written in this documentation https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/6.0-to-7.3.md 

I have installed manually the version 2.1.2 of ruby has explained in the doc

and when doing the database migration  

      bundle exec rake db:migrate RAILS_ENV=production

I got the following error 

```
[git@gobeta gitlab]$  bundle exec rake db:migrate RAILS_ENV=production
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
== 20140416074002 AddIndexOnIid: migrating ====================================
Remove Issue duplicates for iid:  and project_id: 1
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `shift' for #<Issue::ActiveRecord_Relation:0x007f6450b907d8>/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/delegation.rb:136:in `method_missing'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/delegation.rb:99:in `method_missing'
/home/git/gitlab/db/migrate/20140416074002_add_index_on_iid.rb:24:in `block in clean'
/home/git/gitlab/db/migrate/20140416074002_add_index_on_iid.rb:17:in `each'
/home/git/gitlab/db/migrate/20140416074002_add_index_on_iid.rb:17:in `clean'
/home/git/gitlab/db/migrate/20140416074002_add_index_on_iid.rb:3:in `change'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:595:in `exec_migration'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:578:in `block in migrate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:577:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:752:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:992:in `block in execute_migration_in_transaction'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:1040:in `ddl_transaction'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:991:in `execute_migration_in_transaction'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:953:in `block in migrate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:949:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:949:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:807:in `up'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:785:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
NoMethodError: undefined method `shift' for #<Issue::ActiveRecord_Relation:0x007f6450b907d8>
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/delegation.rb:136:in `method_missing'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/relation/delegation.rb:99:in `method_missing'
/home/git/gitlab/db/migrate/20140416074002_add_index_on_iid.rb:24:in `block in clean'
/home/git/gitlab/db/migrate/20140416074002_add_index_on_iid.rb:17:in `each'
/home/git/gitlab/db/migrate/20140416074002_add_index_on_iid.rb:17:in `clean'
/home/git/gitlab/db/migrate/20140416074002_add_index_on_iid.rb:3:in `change'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:595:in `exec_migration'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:579:in `block (2 levels) in migrate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:578:in `block in migrate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:577:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:752:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:992:in `block in execute_migration_in_transaction'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:1040:in `ddl_transaction'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:991:in `execute_migration_in_transaction'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:953:in `block in migrate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:949:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:949:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:807:in `up'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/migration.rb:785:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
```

**Comment by louim** [comment] 2015-01-23 04:21
Can confirm that @artemrizhov fix + pulling the fix from #7443 worked for me (updating from 6.5 to 7.7)

**Comment by topdown** [comment] 2015-04-23 00:26
Just had the same problem going from 6.8 to 7.10
Are there any solutions for this yet?

**Comment by louim** [comment] 2015-04-23 04:02
It will work, but then the migration will never be executed, and that could cause more problems down the road because your schema won't be in sync. I would strongly suggest doing the patch from #7443 and running the delete @artemrizhov posted, after that running a `rake db:migrate` will allow the migration to execute.

**Comment by topdown** [comment] 2015-04-23 13:01
@louim You were correct, some migrations were missed. Thank you.

**Comment by jvanbaarsen** [comment] 2015-11-07 22:18
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Closed by jvanbaarsen** 2015-11-07 22:18 UTC

**Comment by rutsky** [comment] 2016-02-12 16:03
Patch from #7443 and approach presented by @artemrizhov doesn't work for me (and IMO shouldn't).

According to my investigations migration from 6.0 to 6.1 does following related to the Issues ids:

1. In `rake db:migrate` new column `iid` is added.
2. In `rake migrate_iids` column `iid` is filled.

In later versions of Gitlab new DB migrations are added, that uses `iid` column.
If DB migrations from 6.0 to 7.14 are started (as stated in [6.x-or-7.x-to-7.14.md migration guide](https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/6.x-or-7.x-to-7.14.md)), they will fail because one of migrations tries to use `iid` column, which content that is not yet filled (of course, if Gitlab instance has any Issues in database).

To workaround this issue you can do migration as it would be done if you migrated from 6.0 to 6.1 and then to later versions.
Instead of:

```
# Run database migrations
sudo -u git -H bundle exec rake db:migrate RAILS_ENV=production

# Enable internal issue IDs (introduced in GitLab 6.1)
sudo -u git -H bundle exec rake migrate_iids RAILS_ENV=production
```

do:

```
# Run database migrations from 6.0 to 6.1
sudo -u git -H bundle exec rake db:migrate RAILS_ENV=production VERSION=20130909132950

# Enable internal issue IDs (introduced in GitLab 6.1)
sudo -u git -H bundle exec rake migrate_iids RAILS_ENV=production

# Run left database migrations
sudo -u git -H bundle exec rake db:migrate RAILS_ENV=production
```

**Comment by Abdull** [comment] 2016-02-25 14:59
Thank you @rutsky , your suggestions helped us think into the right direction.

First following the official Gitlab migration guide, our migration failed at some particular migration step, namely [20131009115346](https://github.com/gitlabhq/gitlabhq/blob/7-14-stable/db/migrate/20131009115346_add_confirmable_to_users.rb), complaining that some rows already exist.
We then just manually undid that migration step by running the reverse SQL statements:

    alter table users drop column confirmation_token, confirmed_at, confirmation_sent_at, unconfirmed_email;
Then 

    sudo -u git -H bundle exec rake migrate_iids RAILS_ENV=production
    sudo -u git -H bundle exec rake db:migrate RAILS_ENV=production

This successfully completed our 6.0-to-7.14 migration.

**Comment by jblaise** [comment] 2016-03-07 09:20
thanks you @rutsky and @Abdull, your solution was a great help to upgrade from 6.0 to 7.14 !!
