### ISSUE TITLE
gitlab:backup:create error message: fatal: Not a git repository

### ISSUE THREAD

**Issue by rjhornsby** [gitlabhq/gitlabhq#10002] opened 2016-01-25 14:44 UTC
Have started getting this message after upgrading Gitlab to 8.4.0

```
$ sudo gitlab-rake gitlab:backup:create
fatal: Not a git repository (or any parent up to mount point /opt)
Stopping at filesystem boundary (...)
```

For reference, this appears to be similar to #1155.

The backup appears to otherwise complete successfully.  Like the comments in #1155, we are using a different directory for the backups (/var/opt/gitlab/backups), but haven't changed any of the configuration -- just ran the rpm -Uvh to upgrade to 8.4 over the weekend.

I admittedly don't know or understand enough about rake to know where to look to see what is happening behind the scenes of the gitlab-rake command.

**Comment by ilyaevseev** [comment] 2016-01-26 11:47
The same situation after upgrading from 7.9.4-omnibus.1-1 to 8.4.0-ce.0 under Ubuntu 14.04.

     # /opt/gitlab/bin/gitlab-rake gitlab:backup:create CRON=1
     fatal: Not a git repository (or any of the parent directories): .git

/var/opt/gitlab/backups/$TSTAMP_gitlab_backup.tar is created as usual.

**Comment by maxlazio** [comment] 2016-01-26 11:53
Closing as duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/12657 .

**Closed by maxlazio** 2016-01-26 11:53 UTC
