### ISSUE TITLE
Support SVG as an image type

### ISSUE THREAD

**Issue by RandomInsano** [gitlabhq/gitlabhq#9376] opened 2015-06-10 20:02 UTC
It looks like someone has already done a hack to implement this, but having it supported in-tree would be better. Here's the SO page for someone's fix:

http://stackoverflow.com/questions/29982037/gitlab-rails-raw-file-mime-type-for-svg-files-is-text-plain-can-it-be-co

**Comment by Razer6** [comment] 2015-09-05 09:28
Closing as duplicate of #9265

**Closed by Razer6** 2015-09-05 09:28 UTC
