### ISSUE TITLE
Contributions calendar is off by 1 day

### ISSUE THREAD

**Issue by creker** [gitlabhq/gitlabhq#9179] opened 2015-04-23 11:59 UTC
Here's what my calendar looks like
![default](https://cloud.githubusercontent.com/assets/2558271/7296041/a325c3ca-e9c4-11e4-8fd9-1af792c48ecd.png)
The problem is calendar displays wrong contributions. For example, Sunday April 19 is light blue and shows 2 contributions in the tooltip but if I click on it contributions list below is empty, like it should be - I didn't make any contributions on April 19. If I then hover my mouse over Monday April 20, which is gray, in the tooltip it says 0 contributions. Clicking on it - contributions list shows 2 items, like it should be - I did make 2 contributions on April 20.

My timezone is UTC+4

**Comment by lukeknep** [comment] 2015-05-27 20:50
Same issue here. Timzone is PST (GMT-7)

**Comment by Razer6** [comment] 2015-09-05 11:16
Duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/1943

**Closed by Razer6** 2015-09-05 11:16 UTC
