### ISSUE TITLE
502 Bad Gateway when requesting gitlab

### ISSUE THREAD

**Issue by jtherin** [gitlabhq/gitlabhq#9936] opened 2015-12-29 19:33 UTC
I've installed Gitlab CE on a fresh Ubuntu 14.04 via repository without error.
But when I access to gitlab, I get back a 502 Bad Gateway.

tail /var/log/gitlab/nginx/gitlab_error.log :
2015/12/29 20:18:59 [crit] 4331#0: *1 connect() to unix:/var/opt/gitlab/gitlab-workhorse/socket failed (13: Permission denied) while connecting to upstream, client: XX.XX.XX.XX, server: YY.YY.YY.YY, request: "GET / HTTP/1.1", upstream: "http://unix:/var/opt/gitlab/gitlab-workhorse/socket:/", host: "YY.YY.YY.YY"

ls -al /var/opt/gitlab/gitlab-workhorse/socket
srwxr-xr-x 1 git git 0 Dec 29 20:18 /var/opt/gitlab/gitlab-workhorse/socket
if I change chmod to o+w, gitlab is now working (poor solution).

Any idea?

Best regards.

**Comment by stanhu** [comment] 2015-12-29 23:43
These are the permissions I see:

```sh
$ sudo ls -al /var/opt/gitlab/gitlab-workhorse/socket
srwxrwxrwx 1 git git 0 Dec 29 15:28 /var/opt/gitlab/gitlab-workhorse/socket
```

Do you have any idea how the permissions may have been altered?

**Comment by jtherin** [comment] 2015-12-29 23:52
I have no idea, it's a fresh installation of gitlab on a fresh ubuntu with 2gb ram :/
I tried to install gitlab on a second virtual machine and I get the same problem.

If I delete /var/opt/gitlab/gitlab-workhorse/socket and I restart gitlab, it recreates it with srwxr-xr-x.

**Comment by stanhu** [comment] 2015-12-31 07:48
I don't see this issue on two different installations of GitLab 8.3.2 on Ubuntu 14.04. What version of GitLab are you using?

**Comment by Julusian** [comment] 2016-01-03 16:05
I am also getting the same issue with GitLab 8.3.2 on Debian 8

**Comment by jtherin** [comment] 2016-01-03 16:12
I'm using GitLab 8.3.2 (repo version) on Ubuntu 14.04 too.
If I change the chmod, after a reboot it goes to srwxr-xr-x again.

**Comment by stanhu** [comment] 2016-01-04 16:12
I rebooted an Ubuntu 14.04 system and didn't see this problem. Is your installation directory a network-mounted drive per chance? Any ideas how this happens, @maxlazio?

**Comment by viceetversa** [comment] 2016-01-05 13:18
I have the same issue with a fresh installation on Debian 8. Sockets either need to be owned by the Nginx user or put in /run.

The easiest is to change their location to /run/gitlab in /etc/gitlab/gitlab.rb:
```ruby
gitlab_git_http_server['listen_addr'] = '/run/gitlab/gitlab-git-http-server.socket'
unicorn['socket'] = '/run/gitlab/gitlab.socket'
ci_unicorn['socket'] = '/run/gitlab/gitlab-ci.socket'
```
The only issue is that on startup /run gets wipe cleaned and gitlab doesn't have the permission to recreate the sockets. So I need to recreate the gitlab folder on startup, in /etc/rc.local:
```bash
if [ ! -d /run/gitlab ]; then
  mkdir /run/gitlab
  chown git:gitlab-www /run/gitlab/
fi
```

**Comment by viceetversa** [comment] 2016-01-05 14:34
I have the same issue with a fresh install on a Debian 8 VM.

**Comment by Julusian** [comment] 2016-01-05 15:11
I am also running Debian in LXC

**Comment by morph027** [comment] 2016-01-06 08:58
@viceetversa THX, this is working in my LXC Ubuntu (@Proxmox) too!

**Comment by stanhu** [comment] 2016-01-07 01:17
@viceetversa Thanks, AppArmor is a possible culprit. For those of you having trouble, does adding an override in `/etc/apparmor.d/local` also fix the problem? See:

https://opensourcegenie.wordpress.com/2014/11/01/apparmor-permission-issue-with-mysql-on-ubuntu/

**Comment by stanhu** [comment] 2016-01-07 19:39
I'm closing this issue because it seems like it's an issue with external programs changing permissions when they should not be.

**Closed by stanhu** 2016-01-07 19:39 UTC

**Comment by Julusian** [comment] 2016-01-07 21:15
@stanhu In the case of @morph027 and me, apparmor is running on the Proxmox host. Which makes it impractical (and bad practise) to have to add apparmor rules. 

My workaround is to set:
```
gitlab_git_http_server['listen_addr'] = '/tmp/gitlab-workhorse.socket'
```
That works fine without any other changes

**Comment by vialcollet** [comment] 2016-01-31 22:57
The above from @Julusian worked for me using a lxc container (ubuntu 14 and omnibus install) in proxmox.
Thanks!

**Comment by IlyaSemenov** [comment] 2016-04-21 13:54
To the folks from Google: if you are experiencing the same problem running Gitlab with docker, use `docker run -v /run/gitlab/sockets:/home/git/gitlab/tmp/sockets` to store the socket on the docker host and circumvent apparmor protection.

**Comment by psyc0** [comment] 2016-06-18 23:14
@viceetversa ; have you tried 8.8.5 yet? , the gitlab_git_http_server option is no longer present in the gitlab.rb

**Comment by bjarnoldus** [comment] 2016-06-19 11:21
You can also add the www-data user to the gitlab-www group. The permission denied is caused by the following permission:
```
ls -la /var/opt/gitlab/
drwxr-x---  2 git          gitlab-www 4096 Jun 19 13:18 gitlab-workhorse
```
