### ISSUE TITLE
Search does not work with special characters

### ISSUE THREAD

**Issue by geki007** [gitlabhq/gitlabhq#6226] opened 2014-02-03 08:37 UTC
I have problems to find something in my code if i search for words that contain characters like ', <, >

**Comment by milgner** [comment] 2015-01-22 13:38
Also happens when searching for question marks. Probably some missing string escaping.

**Comment by Razer6** [comment] 2015-09-07 08:15
Closing as a duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/2249

**Closed by Razer6** 2015-09-07 08:15 UTC
