### ISSUE TITLE
Restore only 1 repository from gitlab-rake backup

### ISSUE THREAD

**Issue by amitdaniel86** [gitlabhq/gitlabhq#9586] opened 2015-08-26 13:12 UTC
Hi , 

i'm newbie in gitlab so i'm sorry if it's a stupid question .
I'm using gitlab-rake command to backup all my repositories in 1 tar file .
I would like to restore only 1 repository and his branches and i didn't find the command to do that .

Backup command : 

sudo gitlab-rake gitlab:backup:create ( with this command i have the whole branches am i right ? )

Can you share with me the command to restore only 1 repository ?

Thanks , 
Amit Daniel

**Comment by stanhu** [comment] 2015-08-31 01:14
Closing because this is a duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/2397.

**Closed by stanhu** 2015-08-31 01:14 UTC
