### ISSUE TITLE
API project/:id namespace error

### ISSUE THREAD

**Issue by lkoenigsberger** [gitlabhq/gitlabhq#9269] opened 2015-05-08 18:00 UTC
Following problem if I want to access my project over the api with this url:
```
http://example.com/api/v3/projects/user%2Fproject?private_token=XXX
```
I get a 404 not found error, but if I access the project through the project id it works
```
http://example.com/api/v3/projects/2?private_token=XXX
```

I`m using GitLab 7.10.1

**Comment by pulponair** [comment] 2015-08-20 13:40
Confirmed

**Comment by jvanbaarsen** [comment] 2015-12-22 07:31
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Closed by jvanbaarsen** 2015-12-22 07:31 UTC
