### ISSUE TITLE
Support Ruby 2.2

### ISSUE THREAD

**Issue by chulkilee** [gitlabhq/gitlabhq#8696] opened 2015-01-30 18:32 UTC
This is a placeholder for issues on Ruby 2.2

- 500 when deleting a project: #8621 #8624 #8671
- 500 on admin/groups: #8590 #8685
- 500 when adding key or label: #8567

Common pattern is `undefined method `name' for nil:NilClass`

**Comment by fedir** [comment] 2015-02-13 11:05
500 on Remove group

**Comment by MOZGIII** [comment] 2015-03-07 19:49
:+1:

**Comment by Difrex** [comment] 2015-07-17 07:06
:+1:

**Comment by MOZGIII** [comment] 2015-07-17 07:36
Maybe just port to Rails 5+ at some point? It requires Ruby 2.2+.

**Comment by Razer6** [comment] 2015-09-04 16:48
Closing this issue for now.

**Closed by Razer6** 2015-09-04 16:48 UTC

**Comment by fedir** [comment] 2015-09-05 08:42
Actual stable Ruby is 2.2.3. Instead of closing the issue, should find the way to make Gitlab compatible with Ruby 2.2.x.

**Comment by Razer6** [comment] 2015-09-05 08:45
Yes, ruby 2.2.3 is stable but 2.1.6 is stable either ;-) Of course we will update ruby in future, but right now we do not support 2.2. The ruby version requirements are stated in the docs - therefore I closed the issue.

**Comment by fedir** [comment] 2015-09-05 09:41
On ruby's site, 2.1 is marked as "previous stable".

**Comment by simonzack** [comment] 2015-09-15 04:19
:+1: Gitlab's the only package using the old ruby on my system.

**Comment by KingCrunch** [comment] 2015-10-01 21:21
Tbh I am confused. I don't see, that the issue is solved and it is still relevant

**Comment by JobV** [comment] 2015-11-04 15:07
We're doing this for GitLab 8.5: https://gitlab.com/gitlab-org/gitlab-ce/issues/3340
