### ISSUE TITLE
OAuth Login does not redirect to authorization page

### ISSUE THREAD

**Issue by ClassicCut** [gitlabhq/gitlabhq#9396] opened 2015-06-17 15:40 UTC
When using gitlab as an oauth application provider, if I'm prompted to sign-in to gitlab as part of the authorization flow, I am redirected to the home page, rather than the authorize application page, thus kicking me out of the oauth authorization flow.

To reproduce: create an oauth application on gitlab. On an external service configured to use gitlab as an oauth provider, initiate an oauth session (when not currently signed-in to gitlab)

Expected behavior: after logging in, I should be redirected to the authorize application page, prompting me to authorize the requesting application.

Observed behavior: after logging in to gitlab, the oauth flow breaks, and I'm dumped into the gitlab home page/dashboard.

If I'm already logged in to gitlab, the whole oauth authorization flow works as expected.

*edit: I'm experiencing this on both gitlab.com (version 7.12.0-ee) and a private hosted gitlab instance (version 7.11.2)

**Comment by jubianchi** [comment] 2015-06-25 14:21
same here on gitlab 7.10.4 337225a and 7.11.4 b725318

**Comment by varnaudov** [comment] 2015-07-15 11:38
Also verified on GitLab 7.10.4 337225a; this is perhaps related or duplicate of: https://gitlab.com/gitlab-org/gitlab-ce/issues/1612

**Comment by stanhu** [comment] 2015-07-18 16:56
Thanks for the report. I put my notes in that GitLab issue:

https://gitlab.com/gitlab-org/gitlab-ce/issues/1612#note_1645396

I'll close this issue out and refer to that issue.

**Closed by stanhu** 2015-07-18 16:56 UTC

**Comment by stanhu** [comment] 2015-07-19 07:09
Should be fixed via 247609a3d.
