### ISSUE TITLE
Builds job list layout

### ISSUE THREAD

**Issue by cytopia** [gitlabhq/gitlabhq#9847] opened 2015-11-23 09:19 UTC
The job list layout does not scale when having a lot of jobs.

* Tested on Chrome 46.0.2490.86 (64-bit)
* Tested on Firefox 42.0

![screen shot 2015-11-23 at 10 17 36](https://cloud.githubusercontent.com/assets/12533999/11333125/916b47f4-91cb-11e5-9b2d-b1489956ee43.png)

**Comment by Razer6** [comment] 2015-11-23 09:58
Closing as a duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/3384. It is enough to open an issue on gitlab.com

**Closed by Razer6** 2015-11-23 09:58 UTC
