### ISSUE TITLE
Error: This does not look like a tar archive

### ISSUE THREAD

**Issue by vinkla** [gitlabhq/gitlabhq#9775] opened 2015-10-26 19:06 UTC
I'm using [Envoyer](https://envoyer.io) to handle deployments for my PHP applications. You can integrate GitLab into Envoyer to allow it to fetch the archive to deploy on your server. After updating to 8.1.0 yesterday it isn't possible to download the archive anymore? It worked fine before and when I look at the content of the downloaded file it it is a JSON with a absolute path against the archive `tar`. Any ideas why this doesn't work anymore?

```bash
--2015-10-26 08:49:19--  http://git.example.com/api/v3/projects/group%2Fproject/repository/archive?sha=SHA&private_token=theprivatetoken
Resolving git.example.com (git.example.com)... 123.123.123.123
Connecting to git.example.com (git.example.com)|123.123.123.123|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 400 [application/json]
Saving to: ‘/home/user/example.dev/thetarballstring’

0K Unpacking project tarball. 100% 63.2M=0s

2015-10-26 08:49:19 (63.2 MB/s) - ‘/home/user/example.dev/thetarballstring’ saved [400/400]

tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

```

**Comment by vinkla** [comment] 2015-10-27 08:54
I experience the same issue when pressing the archive button. Could this be something with my nginx configuration?
<img width="341" alt="67fhyn7nyxaeaeyqwjyebenrdpzqkm1rod0jou0vhiqbbcchqybk_h1udo1yyg-v3mreu-gzcxndtevcm5fsxn0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85" src="https://cloud.githubusercontent.com/assets/499192/10753317/87350234-7c90-11e5-87f2-bb3a099980f5.png">

**Comment by taylorotwell** [comment] 2015-12-22 14:12
Do we have any updates on this? This is a serious blocking bug in https://envoyer.io right now (I am the maintainer).

**Comment by vinkla** [comment] 2015-12-22 14:15
This works on the latest version of CE version. I solved it by updating the host file.

**Comment by taylorotwell** [comment] 2015-12-22 14:27
I'm using Gitlab.com on Envoyer. Still having the issue.

**Comment by vinkla** [comment] 2015-12-22 14:29
Okay, I've reopened it.

**Comment by Jegulsky** [comment] 2015-12-23 14:41
Could you please raise the priority of this issue? It actually has blocked deployment in my workflow, but as I can see it still not assigned for anyone.

**Comment by taylorotwell** [comment] 2015-12-23 14:49
Yeah, this is a really annoying problem right now.

**Comment by taylorotwell** [comment] 2015-12-23 15:33
Now the endpoint is returning JSON with some junk instead of the actual tar file:

`{"RepoPath":"/var/opt/gitlab/git-data/repositories/taylorotwell/socialite-test.git","ArchivePrefix":"socialite-test-ddae4b34ef3f400fdd63f9e802e17b84f5ed02bd-ddae4b34ef3f400fdd63f9e802e17b84f5ed02bd","ArchivePath":"/var/opt/gitlab/gitlab-rails/shared/cache/archive/socialite-test.git/socialite-test-ddae4b34ef3f400fdd63f9e802e17b84f5ed02bd-ddae4b34ef3f400fdd63f9e802e17b84f5ed02bd.tar.gz","CommitId":"ddae4b34ef3f400fdd63f9e802e17b84f5ed02bd....`}

**Comment by dblessing** [comment] 2015-12-23 21:15
Reported at https://gitlab.com/gitlab-org/gitlab-ce/issues/4279

**Comment by taylorotwell** [comment] 2015-12-23 21:17
Thanks. Hopefully this gets fixed soon. I can't seem to even get confirmation that this bug exists. :frowning:

**Comment by stanhu** [comment] 2015-12-24 22:17
Confirmed. This is a duplicate of these other issues. I've submitted a fix:

https://gitlab.com/gitlab-org/gitlab-workhorse/merge_requests/21

**Closed by stanhu** 2015-12-24 22:17 UTC
