### ISSUE TITLE
post-receive hook not triggered if new tag added via gitlab portal

### ISSUE THREAD

**Issue by mumblez** [gitlabhq/gitlabhq#8619] opened 2015-01-20 23:57 UTC
works when committing and pushing via cli / git tools but if someone creates a new tag via gitlab's interface the post-receive hook is not executed.

Affects version 7.0 (possibly prior) and latest 7.6

Not sure if this is by design, if so can you suggest a way to trigger this on a per repo basis?

(gitlab community edition)

**Comment by minorOffense** [comment] 2015-03-27 11:50
This is still an issue in 7.8.4. Tag push events aren't triggered for tags created through the UI.

**Comment by Razer6** [comment] 2015-09-05 11:32
Duplicate of https://github.com/gitlabhq/gitlabhq/issues/7357

**Closed by Razer6** 2015-09-05 11:32 UTC
