### ISSUE TITLE
All images in help section returns either "404 Not Found" or "500 Internal Server Error" response

### ISSUE THREAD

**Issue by alhashash** [gitlabhq/gitlabhq#7610] opened 2014-08-26 17:13 UTC
When opening the help section, no images are displayed (For example, in backup and workflow/groups sections). 

I tried recompiling assets and restarting gitlab/nginx but got the same errors. The `.png` image files are available at the same location as the `.md` files and `git status` shows no change.

For example, `.../help/workflow/groups/transfer_project.png` returns `404` response. 
`production.log` shows:
```
Started GET "/help/workflow/groups/transfer_project.png" for 192.168.1.19 at 2014-08-26 20:03:56 +0300
Processing by NamespacesController#show as HTML
  Parameters: {"id"=>"help/workflow/groups/transfer_project.png"}
Completed 404 Not Found in 12ms (Views: 4.4ms | ActiveRecord: 2.3ms)
```

`.../help/raketasks/backup_hrz.png` returns `500` response. 
`production.log` shows:
```
Started GET "/help/raketasks/backup_hrz.png" for 192.168.1.19 at 2014-08-26 19:57:15 +0300
Processing by HelpController#show as PNG
  Parameters: {"category"=>"raketasks", "file"=>"backup_hrz"}
Completed 500 Internal Server Error in 6ms

ActionView::MissingTemplate (Missing template errors/not_found with {:locale=>[:en], :formats=>[:png], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :coffee, :haml]}. Searched in:
  * "/home/git/gitlab/app/views"
  * "/home/git/gitlab/vendor/bundle/ruby/gems/semantic-ui-sass-0.16.1.0/app/views"
  * "/home/git/gitlab/vendor/bundle/ruby/gems/kaminari-0.15.1/app/views"
  * "/home/git/gitlab/vendor/bundle/ruby/gems/devise-3.2.4/app/views"
  * "/home/git/gitlab"
  * "/"
):
  app/controllers/application_controller.rb:140:in `not_found!'
  app/controllers/help_controller.rb:12:in `show'
```

Here is the setup information:
```
System information
System:
Current User:   git
Using RVM:      no
Ruby Version:   2.0.0p353
Gem Version:    2.0.14
Bundler Version:1.7.2
Rake Version:   10.3.2
Sidekiq Version:2.17.0

GitLab information
Version:        7.2.0
Revision:       935ed64
Directory:      /home/git/gitlab
DB Adapter:     postgresql
URL:            https://xxx.xxxxxx.com
HTTP Clone URL: https://xxx.xxxxxx.com/some-project.git
SSH Clone URL:  git@xxx.xxxxxx.com:some-project.git
Using LDAP:     no
Using Omniauth: no

GitLab Shell
Version:        1.9.7
Repositories:   /home/git/repositories/
Hooks:          /home/git/gitlab-shell/hooks/
Git:            /usr/bin/git
```

**Comment by nikolov-tmw** [comment] 2015-01-22 18:55
I can confirm that this is still the case with 7.7.0

**Comment by junxy** [comment] 2015-01-26 02:19
+1 
On `GitLab 7.7.0 c04f11d`

newrelic error events
```
Error message
ActionView::MissingTemplate: Missing template errors/not_found with {:locale=>[:en], :formats=>[:png], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :slim, :coffee, :haml]}. Searched in: * "/home/git/gitlab/app/views" * "/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/semantic-ui-sass-0.16.1.0/app/views" * "/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/kaminari-0.15.1/app/views" * "/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/doorkeeper-2.1.0/app/views" * "/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/devise-3.2.4/app/views" * "/home/git/gitlab" * "/"

Sample stack trace (show Rails)
….1.0/gems/actionview-4.1.1/lib/action_view/
path_set.rb:  46:in `find'
…ems/actionview-4.1.1/lib/action_view/
lookup_context.rb: 124:in `find'
…ew-4.1.1/lib/action_view/renderer/
abstract_renderer.rb:  18:in `find_template'
…ew-4.1.1/lib/action_view/renderer/
template_renderer.rb:  33:in `block in determine_template'
…ems/actionview-4.1.1/lib/action_view/
lookup_context.rb: 145:in `with_fallbacks'
…ew-4.1.1/lib/action_view/renderer/
abstract_renderer.rb:  18:in `with_fallbacks'
…ew-4.1.1/lib/action_view/renderer/
template_renderer.rb:  33:in `determine_template'
…ew-4.1.1/lib/action_view/renderer/
template_renderer.rb:   8:in `render'
…/actionview-4.1.1/lib/action_view/renderer/
renderer.rb:  42:in `render_template'
…/actionview-4.1.1/lib/action_view/renderer/
renderer.rb:  23:in `render'
…1.0/gems/actionview-4.1.1/lib/action_view/
rendering.rb:  99:in `_render_template'
…1.0/gems/actionview-4.1.1/lib/action_view/
rendering.rb:  82:in `render_to_body'
…e/git/gitlab/app/controllers/
application_controller.rb: 142:in `not_found!'
    /home/git/gitlab/app/controllers/
help_controller.rb:  12:in `show'
…1.0/gems/actionview-4.1.1/lib/action_view/
rendering.rb:  30:in `process'
…uby/2.1.0/gems/omniauth-1.1.4/lib/omniauth/
strategy.rb: 184:in `call!'
…uby/2.1.0/gems/omniauth-1.1.4/lib/omniauth/
strategy.rb: 164:in `call'
…ms/request_store-1.0.5/lib/request_store/
middleware.rb:   9:in `call'
…undle/ruby/2.1.0/gems/rack-cors-0.2.9/lib/rack/
cors.rb:  54:in `call'
…e/ruby/2.1.0/gems/rack-attack-4.2.0/lib/rack/
attack.rb: 104:in `call'
…dle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/
manager.rb:  35:in `block in call'
…dle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/
manager.rb:  34:in `catch'
…dle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/
manager.rb:  34:in `call'
…dor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/
etag.rb:  23:in `call'
…/ruby/2.1.0/gems/rack-1.5.2/lib/rack/
conditionalget.rb:  25:in `call'
…dor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/
head.rb:  11:in `call'
…/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/
id.rb: 225:in `context'
…/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/
id.rb: 220:in `call'
```

**Comment by HofmeisterAn** [comment] 2015-02-12 15:19
+1 I have the same problem. Please notice the second `help` in the adress: `help/help/api/README.md`. Every link in the root help section, has this additional item.

```
https://gitlab.example.com/help/help/api/README.md
https://gitlab.example.com/help/help/markdown/markdown.md
...
```

```
==> /var/log/gitlab/gitlab-rails/production.log <==
Started GET "/help/help/markdown/markdown.md" for 127.0.0.1 at 2015-02-12 16:11:
Processing by NamespacesController#show as HTML
  Parameters: {"id"=>"help/help/markdown/markdown.md"}
Completed 404 Not Found in 16ms (Views: 1.1ms | ActiveRecord: 2.6ms)

==> /var/log/gitlab/nginx/gitlab_access.log <==
172.16.100.254 - - [12/Feb/2015:16:11:25 +0100] "GET /help/help/markdown/markdow                                                                                                                                                             L, like Gecko) Chrome/40.0.2214.111 Safari/537.36"
```

**Comment by aureliojargas** [comment] 2015-03-26 17:27
As quick temporary fix, you can copy all the images to the `public/help` folder, as  shown in this commit: https://github.com/rumpelsepp/gitlab-pkgbuilds/commit/68937d754bb98dbd8cd03991df59f2e65f7b51c7

```console
cd /opt/gitlab/embedded/service/gitlab-rails
cp -r doc public/help
find public/help/ -name "*.md" -exec rm {} \;
find public/help/ -depth -type d -empty -exec rmdir {} \;
```

**Comment by Razer6** [comment] 2015-04-03 10:50
Closing because fix is merged.

**Closed by Razer6** 2015-04-03 10:50 UTC
