### ISSUE TITLE
Sign Out not working

### ISSUE THREAD

**Issue by santosh0705** [gitlabhq/gitlabhq#10061] opened 2016-03-02 05:47 UTC
User sign out link renders to 404

**Comment by rymai** [comment] 2016-03-02 09:23
@santosh0705 Thanks for the issue report. It works for me on latest GitLab 8.5.2. Please reformat your issue to conform to the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by santosh0705** [comment] 2016-03-02 09:38
I tested using docker images versions: 8.5.1-ce.0 and 8.4.5-ce.0
both having same issue.

**Comment by santosh0705** [comment] 2016-03-02 13:09
## Summary

The user sign out is not working.

## Steps to reproduce

This problem is with the docker Gitlab community edition based images. To regenerate run the latest gitlab-ce docker image from docker hub. tested with the following versions: `8.5.1-ce.0` and `8.4.5-ce.0`
You also need to create the `logs/reconfigure` directory in latest version.

## Expected behavior

It should sign out the logged in user and return the login page.

## Relevant logs and/or screenshots

Instead signing out user it renders HTTP 404 page

```
404
The page you're looking for could not be found.

Make sure the address is correct and that the page hasn't moved.

Please contact your GitLab administrator if you think this is a mistake.
```

## Output of checks

### Results of GitLab Application Check

output of `gitlab-rake gitlab:check SANITIZE=true`

```
Checking GitLab Shell ...

GitLab Shell version >= 2.6.10 ? ... OK (2.6.10)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
hooks directories in repos are links: ... can't check, you have no projects
Running /opt/gitlab/embedded/service/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
	/var/opt/gitlab/git-data/repositories: OK
	/var/opt/gitlab/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.21
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking Reply by email ...

Reply by email is disabled in config/gitlab.yml

Checking Reply by email ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Git configured with autocrlf=input? ... yes
Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Uploads directory setup correctly? ... skipped (no tmp uploads folder yet)
Init script exists? ... skipped (omnibus-gitlab has no init script)
Init script up-to-date? ... skipped (omnibus-gitlab has no init script)
projects have namespace: ... can't check, you have no projects
Redis version >= 2.8.0? ... yes
Ruby version >= 2.1.0 ? ... yes (2.1.8)
Your git bin path is "/opt/gitlab/embedded/bin/git"
Git version >= 1.7.10 ? ... yes (2.6.2)
Active users: 1

Checking GitLab ... Finished
```

### Results of GitLab Environment Info

output of `gitlab-rake gitlab:env:info`

```
System information
System:		Ubuntu 14.04
Current User:	git
Using RVM:	no
Ruby Version:	2.1.8p440
Gem Version:	2.5.1
Bundler Version:1.10.6
Rake Version:	10.5.0
Sidekiq Version:4.0.1

GitLab information
Version:	8.4.5
Revision:	fed33aa
Directory:	/opt/gitlab/embedded/service/gitlab-rails
DB Adapter:	postgresql
URL:		http://gitlab.locuz.com
HTTP Clone URL:	http://gitlab.locuz.com/some-group/some-project.git
SSH Clone URL:	git@gitlab.locuz.com:some-group/some-project.git
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	2.6.10
Repositories:	/var/opt/gitlab/git-data/repositories
Hooks:		/opt/gitlab/embedded/service/gitlab-shell/hooks/
Git:		/opt/gitlab/embedded/bin/git
```

Hope the above info is sufficient

**Comment by santosh0705** [comment] 2016-03-03 08:42
I tested the newest docker image version `8.5.2-ce.0` but the problem is still there.

**Comment by Razer6** [comment] 2016-03-03 12:47
@santosh0705 Do you have javascript disabled?

**Comment by santosh0705** [comment] 2016-03-03 12:52
Javascript is not disable. Its definitely not an issue of javascript. If simply throwing HTTP 404 on signout url

**Comment by Razer6** [comment] 2016-03-03 13:35
Is it reproducible for you on gitlab.com?

**Comment by santosh0705** [comment] 2016-03-05 12:16
I figured out the problem. My Gitlab setup sits behind a Nginx reverse proxy and the signout process is an http post which is not happening dont know why. Let me check if any setting I'm missing in Nginx.

**Comment by connorshea** [comment] 2016-05-25 19:20
Closing since this is resolved.

**Closed by connorshea** 2016-05-25 19:20 UTC
Labels: Awaiting feedback
