### ISSUE TITLE
Upgrade to 7.7 limits Milestone issue filter functionality

### ISSUE THREAD

**Issue by timmyjimi** [gitlabhq/gitlabhq#8765] opened 2015-02-09 21:55 UTC
Once I select a Milestone filter on the Issue list, I can’t select a different Milestone until I revert back to an “all” view.

**Comment by Razer6** [comment] 2015-02-25 18:52
Closing as a duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/1035

**Closed by Razer6** 2015-02-25 18:52 UTC

**Comment by timmyjimi** [comment] 2015-02-25 21:45
Thanks, but that link doesn't work for me.

**Comment by Razer6** [comment] 2015-02-25 21:52
@timmyjimi How does this link not work?

**Comment by timmyjimi** [comment] 2015-02-25 22:29
"This webpage is not available"

**Comment by Razer6** [comment] 2015-02-25 22:30
That is strange. Can you access https://gitlab.com /cc @dosire

**Comment by dosire** [comment] 2015-02-25 22:39
@Razer6 Thanks for the ping but I don't know what to do here.

**Comment by timmyjimi** [comment] 2015-02-26 01:39
No luck.
