### ISSUE TITLE
Ruby version reporting in conflict

### ISSUE THREAD

**Issue by Libbux** [gitlabhq/gitlabhq#8391] opened 2014-11-25 16:48 UTC
I'm running GitLab 7.5 on Ubuntu 14.04. I used to be running an outdated version of ruby (see issue #8115 and #8146), and since updating, GitLab has been showing the wrong ruby version in the web admin panel (it reports 1.9.3p484), while running the GitLab check rake task shows the following:

```
Ruby version >= 2.0.0 ? ... yes (2.0.0)
```

The ruby binary in `/usr/bin/` points to the correct executable, and the service has been restarted multiple times since updating.

Thanks

**Comment by Razer6** [comment] 2015-02-12 17:10
This seems to be a duplicate of https://github.com/gitlabhq/gitlabhq/issues/8045

**Closed by Razer6** 2015-02-12 17:10 UTC
