### ISSUE TITLE
Getting "unable to create threaded lstat"

### ISSUE THREAD

**Issue by lokeshkumar** [gitlabhq/gitlabhq#8524] opened 2014-12-31 09:53 UTC
Hi all,

While opening a merge request we got "500: Internal server error" for http://gitlab/<PROJECT>/<MERGE_ID>/automerge_check

We found the below error logs while analysing the issue

Grit::Git::CommandFailed (Command failed [128]: /usr/bin/git --git-dir=/home/git/gitlab-satellites/repositories/testproject/.git --work-tree=/home/git/gitlab-satellites/repositories/testproject checkout -b __parking_branch

fatal: unable to create threaded lstat
):
  lib/gitlab/satellite/satellite.rb:101:in `delete_heads!'
  lib/gitlab/satellite/satellite.rb:23:in `clear_and_update!'
  lib/gitlab/satellite/action.rb:40:in `prepare_satellite!'
  lib/gitlab/satellite/merge_action.rb:15:in `block in can_be_merged?'
  lib/gitlab/satellite/action.rb:24:in `block (2 levels) in in_locked_and_timed_satellite'
  lib/gitlab/satellite/satellite.rb:56:in `block in lock'
  lib/gitlab/satellite/satellite.rb:53:in `open'
  lib/gitlab/satellite/satellite.rb:53:in `lock'
  lib/gitlab/satellite/action.rb:23:in `block in in_locked_and_timed_satellite'
  lib/gitlab/satellite/action.rb:22:in `in_locked_and_timed_satellite'
  lib/gitlab/satellite/merge_action.rb:14:in `can_be_merged?'
  app/models/merge_request.rb:176:in `check_if_can_be_merged'
  app/controllers/projects/merge_requests_controller.rb:107:in `automerge_check'

We tried to restart the gitlab and after restarting gitlab it works fine.

I don't know what is the probelm and its root cause.

Please help me to fix this issue.

Thanks in advance

Regards,
Lokesh

**Comment by vchand** [comment] 2015-04-07 08:28
fdgdf

**Comment by vchand** [comment] 2015-04-07 08:29
git status
fatal: unable to create threaded lstat
anyone having idea about this error

**Comment by pshegde** [comment] 2015-05-21 00:25
Facing the same issue. git status, git checkout not working. Please help!

**Comment by garrison** [comment] 2015-10-07 21:55
The root cause is [this line](https://github.com/git/git/blob/77bd3ea9f54f1584147b594abc04c26ca516d987/preload-index.c#L96) in git.  The `pthread_create` is failing, perhaps due to some resource limit on the number of threads allowed by the user.

**Comment by marksantcroos** [comment] 2015-11-05 08:27
Im getting the same error while running "git diff".

**Comment by garrison** [comment] 2015-11-05 16:19
In my case, putting `ulimit -s unlimited` in my `~/.bashrc` fixed the issue (once I logged in again).

**Comment by marksantcroos** [comment] 2015-11-05 16:25
Thanks @garrison, does the trick for me too!

**Comment by jvanbaarsen** [comment] 2016-01-21 07:22
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Closed by jvanbaarsen** 2016-01-21 07:22 UTC
