### ISSUE TITLE
Git commits starting with an emoji don't show the rest of the message in gitlab

### ISSUE THREAD

**Issue by dlbrown06** [gitlabhq/gitlabhq#9620] opened 2015-09-11 13:39 UTC
When I make a commit like this:
```
:bug: Make a awesome new bug fix

* this is another message relating to what was fixed specifically
```
Then in GitLab it only shows:
```
:bug:

* this is another message relating to what was fixed specifically
```

**Comment by Razer6** [comment] 2015-09-11 15:44
Closing as a duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/2349

**Closed by Razer6** 2015-09-11 15:44 UTC
