### ISSUE TITLE
failed update from 7.8.4 to 7.9 via upgrader.md

### ISSUE THREAD

**Issue by fidomax** [gitlabhq/gitlabhq#8993] opened 2015-03-21 04:30 UTC
upgrader.md script has no 
```bash
sudo apt-get install nodejs
```
so update failed

**Comment by stanhu** [comment] 2015-03-22 05:48
Are you using Debian? This might be a duplicate of #8984.

Also keep in mind the `nodejs` packet is only necessary if you are installing GitLab from source. If you are using the omnibus packages, this step is not required.

**Comment by axilleas** [comment] 2015-03-22 11:49
Closing as duplicate.

**Closed by axilleas** 2015-03-22 11:49 UTC

**Comment by fidomax** [comment] 2015-03-26 05:10
I'm using ubuntu. We need to add check for installed packages: nodejs and etc...
