### ISSUE TITLE
After login line number is lost

### ISSUE THREAD

**Issue by kimegede** [gitlabhq/gitlabhq#3551] opened 2013-04-09 09:31 UTC
If you not logged in, and following a link to a file with a line number, the line number is lost after logging in.

Was excepting the line number to still be there.

**Comment by axilleas** [comment] 2015-03-01 15:39
Still in 7.8

**Comment by samrocketman** [comment] 2015-05-18 00:13
Is it possible it is being stripped by nginx or Apache httpd?

**Comment by stanhu** [comment] 2015-07-06 22:55
I just took a look at this and confirmed this is still an issue in GitLab v7.12, but there isn't a great solution. The issue is that URL fragments (e.g. `#L1`) never [get sent to the server](https://en.wikipedia.org/wiki/Fragment_identifier):

> When an agent (such as a Web browser) requests a web resource from a Web server, the agent sends the URI to the server, but does not send the fragment. Instead, the agent waits for the server to send the resource, and then the agent processes the resource according to the document type and fragment value.

There is some discussion here about working around this problem by injecting the hash on client-side code:

http://stackoverflow.com/questions/17982594/how-do-i-preserve-uri-fragment-in-safari-upon-redirect

**Comment by kimegede** [comment] 2015-07-07 08:52
You are right - I only see 2 solutions:
* don't use hashtag/fragment
* catch the fragment in js (?)

Doesn't seem to be a deal breaker since it have been reported for 2 years ago :)

**Comment by jvanbaarsen** [comment] 2015-12-07 07:44
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Closed by jvanbaarsen** 2015-12-07 07:44 UTC
Labels: Confirmed issue

**Comment by kimegede** [comment] 2015-12-07 08:09
I would say it's still doesn't take me to the expected location, if it haven't been fixed. (I don't use GitLab anymore, not going to report it again).
Someone else, feel free to do so, and maybe add a link here and there :)
