### ISSUE TITLE
Can't delete ghost branches

### ISSUE THREAD

**Issue by Soullivaneuh** [gitlabhq/gitlabhq#8720] opened 2015-02-03 10:29 UTC
In one project of our Gitlab, we have some ghost branches starting by `origin/*`:

![gitlab_branches_remove_fail](https://cloud.githubusercontent.com/assets/1698357/6018349/4ad38e4e-ab96-11e4-984f-f63395f676bc.png)

I'm talking about ghost branches because this branches doesn't appear on git cli:

```sh
# Did it after a fresh git clone of the project.
$ git branch --all
* master
  remotes/origin/846
  remotes/origin/860
  remotes/origin/886
  remotes/origin/926
  remotes/origin/928
  remotes/origin/935
  remotes/origin/938
  remotes/origin/HEAD -> origin/master
  remotes/origin/dc
  remotes/origin/develop
  remotes/origin/hotfix
  remotes/origin/master
  remotes/origin/pre_production
  remotes/origin/unit_tests
```

As you can see branch `origin/11_Finalisation_outil_reporting` and `origin/CGU_FRONT` seems to not exists.

And it's just an example. For this project, gitlab web GUI is showing 131 branches, most starting by `origin/` name.

If I try to delete one of this branch on GUI, the webserver response seems to be OK, but the concerned branch reappear immediately if I refresh the branches list page.

Here, an extract of `production.log`:

```
Started DELETE "/mygroup/www/branches/origin/11_Finalisation_outil_reporting" for 127.0.0.1 at 2015-02-03 11:24:21 +0100
Processing by Projects::BranchesController#destroy as JS
  Parameters: {"project_id"=>"mygroup/www", "id"=>"origin/11_Finalisation_outil_reporting"}
Completed 200 OK in 305ms (Views: 8.0ms | ActiveRecord: 2.6ms)
Started GET "/mygroup/www/branches" for 127.0.0.1 at 2015-02-03 11:24:22 +0100
Processing by Projects::BranchesController#index as HTML
  Parameters: {"project_id"=>"mygroup/www"}
Completed 200 OK in 161ms (Views: 140.0ms | ActiveRecord: 4.1ms)
```

I don't have any more information, can't determinate the source of the problem.

I'm using:
 * Gitlab -> `7.7.2 bd98290`, latest version
 * Gitlab shell -> `2.4.2`
 * git -> `1.8.5.2`

Thanks for your help.

**Comment by Soullivaneuh** [comment] 2015-02-03 10:59
Additional information:

```bash
# Another project:
root@server:/var/git/repositories/mygroup/test.git/refs# ls
heads  tags
# Concerned project:
root@server:/var/git/repositories/mygroup/www.git/refs# ls
heads  remotes  tags
```

In the `remotes` directory, I found an `origin` directory which contains all the "ghost" branches.

How this branch could be here? How to properly delete it?

Hope it's help.

**Comment by gallart** [comment] 2015-02-10 09:06
UP !

**Comment by lifeofguenter** [comment] 2015-03-01 11:05
same here

**Comment by dshoreman** [comment] 2015-03-11 18:41
I had the same issue, although I also had a bunch of ghost branches left over from when I had a `github` remote too. In addition to this, there was a stale remote branch showing when I did `git branch -av`.

The stale local branch was fixed with a quick `git remote prune origin` (you might want to add the `--dry-run` option though).

Once I got everything looking as I wanted it in my local repo (i.e. only `master` and `develop`), I ran `git push --mirror` and the ghost branches haven't come back like they usually would.

It's probably not the best solution, but it's one that worked for me on a solo project. If there are others on the project, it might not be that simple.

**Comment by stan** [comment] 2015-05-06 17:41
same issue

**Comment by stan** [comment] 2015-06-25 11:08
Meanwhile if you want to get rid of those ghost branches, you can run `git push origin --delete ghostbranch` from the command line

**Comment by Razer6** [comment] 2015-10-28 16:37
Closing as a duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/2921

**Closed by Razer6** 2015-10-28 16:37 UTC

**Comment by Soullivaneuh** [comment] 2015-10-28 16:43
Well, this issue is older. The new one should be closed to follow more history IMHO.

**Comment by Razer6** [comment] 2015-10-28 16:54
Right now, we are in the process of shifting most of the stuff to GitLab.com. I see that this is older, however I backlinked this issue so if someone reads either this or the other issue has all the information

**Comment by joecolocon** [comment] 2015-12-02 14:37
Only a little comment.

I'm in same situation.
I had imported from SVN a converted git repo to  gitlab-ce.
This  action had produced a lot of "ghost" remote references. 

I just tried to remove the folder "remotes" commented before and all goes well for me.
