### ISSUE TITLE
Failing to precompile assets on ARM devices (rpi2)

### ISSUE THREAD

**Issue by habovh** [gitlabhq/gitlabhq#8809] opened 2015-02-17 17:49 UTC
# Failing to precompile assets
Hi, based on `@gitlab`'s suggestion on Twitter, I'm opening a new issue.

## Setup

I'm trying to get GitLab to run on my new Raspberry Pi2.
Rasbian Wheezy, GitLab 7.8 manual install, `gitlab` user (home in `/home/gitlab/`).

I keep getting 500/502 Internal Errors when trying to access GitLab through my browser.

## Issue
I followed instructions available [here](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/installation.md).
I can't pass the `assets:precompile` Rake task.

On the first time I call the `assets:precompile` I got the following output : 
```console
gitlab@raspberrypi2 ~/gitlab $ bundle exec rake assets:precompile RAILS_ENV=production
I, [2015-02-17T19:48:20.166277 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/authbuttons/github_32-7d27fb74a3e4e37d32715ce9d0c4a046.png
I, [2015-02-17T19:48:20.179059 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/authbuttons/github_64-a7cc3191da95716c5adc9539375f5039.png
I, [2015-02-17T19:48:20.190249 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/authbuttons/gitlab_32-c875a1bb007a0ea665d8f7dedb0efa7f.png
I, [2015-02-17T19:48:20.201338 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/authbuttons/gitlab_64-631794613bc4968957c5f8629a8a8dfd.png
I, [2015-02-17T19:48:20.212372 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/authbuttons/google_32-b10b264a166cc34878a88cdd36ec5165.png
I, [2015-02-17T19:48:20.223563 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/authbuttons/google_64-26dc05efbdd12c270656910d54aff3f4.png
I, [2015-02-17T19:48:20.234513 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/authbuttons/twitter_32-911ea9b6556d58a5e087ffbd55b1a562.png
I, [2015-02-17T19:48:20.245728 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/authbuttons/twitter_64-51840a5815a8315635015d82bd327146.png
I, [2015-02-17T19:48:20.257579 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/bg-header-977c6f0a15f37a9a5e26bbf4f0b0d081.png
I, [2015-02-17T19:48:20.269518 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/bg_fallback-ffc8b1e489fbe5b4f787aeae6d77d069.png
I, [2015-02-17T19:48:20.283527 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/brand_logo-445c4e7be6b15fa54811b7f9d632a145.png
I, [2015-02-17T19:48:20.295964 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/chosen-sprite-0583558d5932d5ae87d10611631af15c.png
I, [2015-02-17T19:48:20.307669 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/dark-scheme-preview-02cc0d738e463afd221218d83f66cfbf.png
I, [2015-02-17T19:48:20.320040 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/diff_note_add-5ecd142fbfc2979fad93f06173ac3454.png
I, [2015-02-17T19:48:20.334514 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/favicon-baaa14bade1248aa6165e9d34e7d83c0.ico
I, [2015-02-17T19:48:20.346856 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/icon-link-6b3e2754f06ebd3b40eaa8d15689533f.png
I, [2015-02-17T19:48:20.358937 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/icon-search-342ad6afc59f7a08a0403ca575f4540f.png
I, [2015-02-17T19:48:20.371082 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/icon_sprite-12145c1d5e004150a79070c63cc666a3.png
I, [2015-02-17T19:48:20.383257 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/images-f2b97e0e1f2e816619adde04ad9918b2.png
I, [2015-02-17T19:48:20.395310 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/logo-black-96ddf523e8b72d84f4fb03f6c1b695b2.png
I, [2015-02-17T19:48:20.407592 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/logo-white-ed4a8c29c69c582954818a833b737e7a.png
I, [2015-02-17T19:48:20.419767 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/monokai-scheme-preview-aa17467c476f5b39e34ef520b779e0a2.png
I, [2015-02-17T19:48:20.431805 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/move-9e32cd93c6bbbbcc9f7653d4e38f279a.png
I, [2015-02-17T19:48:20.443682 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/no_avatar-3656d6f42d5007925a0cfb4b1e3bb1f1.png
I, [2015-02-17T19:48:20.455567 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/no_group_avatar-9b1c46c6baa02cd6ef73f07b40b685b5.png
I, [2015-02-17T19:48:20.467496 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/onion_skin_sprites-5e76cd26dc318146c4a876441a30b346.gif
I, [2015-02-17T19:48:20.479359 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/progress_bar-a0abc863428b4a7f762159b534f5150f.gif
I, [2015-02-17T19:48:20.491521 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/slider_handles-e6ac44e749b77d27185740f87360c9bf.png
I, [2015-02-17T19:48:20.503712 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/solarized-dark-scheme-preview-19ef84fdbf504b4824de3b3ae2305465.png
I, [2015-02-17T19:48:20.515809 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/solarized-light-scheme-preview-a5e24132d22dcb76561e9c44ff746025.png
I, [2015-02-17T19:48:20.528083 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/swipemode_sprites-c2201e0b316d93c3d7155a2c3979fe89.gif
I, [2015-02-17T19:48:20.540205 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/switch_icon-f562041c089581e1bce91d98e829e8b9.png
I, [2015-02-17T19:48:20.552219 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/trans_bg-f8699c40e0bd968506d0716a7deecb16.gif
I, [2015-02-17T19:48:20.564382 #4106]  INFO -- : Writing /home/gitlab/gitlab/public/assets/white-scheme-preview-8b9b00cb4197a63d622037cf3ca74118.png
rake aborted!
/home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/trace_output.rb:16:in `block in trace_on': invalid byte sequence in UTF-8 (ArgumentError)
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/trace_output.rb:14:in `map'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/trace_output.rb:14:in `trace_on'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:376:in `trace'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:222:in `display_exception_message_details'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:209:in `display_exception_details'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:198:in `display_error_message'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:185:in `rescue in standard_exception_handling'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
gitlab@raspberrypi2 ~/gitlab $ 
```

So, as you can see, Rake manages to process some files, however will eventually crash at some point.
Later, adding the `--trace` option, I got this output :

```console
jordan@raspberrypi2 /home/gitlab/gitlab $ sudo -u gitlab -H bundle exec rake assets:precompile RAILS_ENV=production --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
rake aborted!
/home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/trace_output.rb:16:in `block in trace_on': invalid byte sequence in UTF-8 (ArgumentError)
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/trace_output.rb:14:in `map'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/trace_output.rb:14:in `trace_on'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:376:in `trace'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:222:in `display_exception_message_details'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:209:in `display_exception_details'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:198:in `display_error_message'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:185:in `rescue in standard_exception_handling'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
	from /home/gitlab/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
```

I don't know anything about Rake, so I'm not really able to dig to find out what's wrong... Any clues?
Adding a 1GB swap file to the system did not help. Keep in mind that RPi2 has already got 1GB physical RAM.

Note:
> When running `sudo -u gitlab -H bundle exec rake gitlab:check RAILS_ENV=production` everything is green.

Note 2:
> Maybe related closed issue : https://github.com/gitlabhq/gitlabhq/issues/6642#issuecomment-74453321

# Update 1
If assets are compiled in the alphabetical order from the `app/assets/` folder, the next asset to be compiled after `white-scheme-preview.png` would be the CoffeeScript file `app/assets/javascripts/activities.js.coffee`. Maybe a good lead would be to check if CoffeeScript compiler is accessible to Rake ? Again, I dont know anything about Rake, nor Ruby actually, so this is just suppositions...

**Comment by mbiskach** [comment] 2015-03-01 20:59
I can confirm this issue on my RPi2 following [installation.md on Github](https://github.com/gitlabhq/gitlabhq/blob/7-7-stable/doc/install/installation.md) plus [RPi specific improvements](https://midnightcodr.github.io/2014/01/11/install-gitlab-6-dot-4-on-raspberry-pi/).

I previously had no issues following the exact same install process on my original RPi B which is running like a champ. I was hoping to see some improved performance with the RPi2 when I ran into this issue.

**Comment by dosire** [comment] 2015-03-03 18:31
Anybody has an idea why this happens? Is this RPi only?

**Comment by toborrow** [comment] 2015-03-04 10:56
Actually it seems to be RPi only since TheRubyRacer does not work on it for now. To palliate the issue, if you read [the link mbiskach shared](https://midnightcodr.github.io/2014/01/11/install-gitlab-6-dot-4-on-raspberry-pi/), that I followed too, we manually remove TheRubyRacer from the Gemfile dependancies, and compile Libv8 on our side.

**Comment by dosire** [comment] 2015-03-04 23:28
Wow, if you google 'gitlab rubyracer' you get a lot of links about this /cc @vsizov

**Comment by axilleas** [comment] 2015-03-04 23:43
No need to install therubyracer whatsoever. Install nodejs instead and patch `Gemfile` and `Gemfile.lock` with:

```bash
sed -ri '/therubyracer|libv8|ref/d' Gemfile{,.lock}
```

`therubyracer` is needed by [execjs](https://github.com/sstephenson/execjs#execjs), but as you can see in the readme it supports other runtimes, one of which is nodejs. 

That's how I used it to package it for archlinux arm, see https://github.com/axilleas/pkgbuilds/blob/master/gitlab/PKGBUILD#L99

**Comment by dosire** [comment] 2015-03-05 01:49
Also reported by https://twitter.com/HLFH_Space/status/573276320349724673

**Comment by dosire** [comment] 2015-03-05 03:24
GitLab 7.8 ships with Nodejs so we should be able to avoid the Rubyracer. /cc @randx

**Comment by dosire** [comment] 2015-03-05 03:39
You can safely remove therubyracer from the gemfile if you install nodejs.

We're working on a better fix in https://gitlab.com/gitlab-org/omnibus-gitlab/issues/449

Help in the form of tested merge requests is appreciated.

**Comment by toborrow** [comment] 2015-03-05 19:38
Hi, I just tested your solution @axilleas, but as I said earlier, I followed [this tutorial](https://midnightcodr.github.io/2014/01/11/install-gitlab-6-dot-4-on-raspberry-pi/) to adapt GitLab installation to Raspberry Pi. It contains basically the same instructions (remove RubyRacer and libv8 from Gemfiles, install node).
Therefore, both of these solutions does not work.
I just tried again, on a fresh new install, and I ended up having the exact same error that is reported in my OP.

What does this mean? It basically means that despite the fact that TheRubyRacer does not work *as is* on ARM-based computers, Rake still outputs the **invalid byte sequence in UTF-8** when trying to precompile assets.

**Comment by ZJvandeWeg** [comment] 2015-03-06 13:08
@axilleas
Just confirming that works for me on RPI2. 
Added nodejs as dependency in the PKGBUILD.

**Comment by toborrow** [comment] 2015-03-06 13:33
@ZJvandeWeg Did you change something else for the install to succeed?

**Comment by axilleas** [comment] 2015-03-06 14:01
@toborrow , @ZJvandeWeg probably uses Archlinux arm. If you have a spare SD card try installing Arch. I guess it has something to do with OSes?

**Comment by ZJvandeWeg** [comment] 2015-03-06 14:13
@toborrow @axilleas 
Arch ARM indeed.

**Comment by toborrow** [comment] 2015-03-06 14:17
Oh okay... I may migrate then! I'm currently on Raspbian...

**Comment by ZJvandeWeg** [comment] 2015-03-06 14:56
Raspbian is debian based right? Not really familiar with it, but I just took a quick look at the tutorial you posted and was thinking, why not install nodejs from repo's and just manually remove the rubyracer in the Gemfile en Gemfile.lock?

**Comment by mbiskach** [comment] 2015-03-06 16:24
@ZJvandeWeg, for my RPi2 with latest Raspbian, I have previously tried what you proposed while following [these instructions](https://midnightcodr.github.io/2014/01/11/install-gitlab-6-dot-4-on-raspberry-pi/) which worked for my older RPiB. What I have not done is tried this approach using Arch Linux.

Has anyone successfully compiled assets for RPi2 with Raspbian by installing nodejs from repo, and modifying Gemfile/Gemfile.lock??

**Comment by toborrow** [comment] 2015-03-07 03:52
Ok guys, you'll have to forgive me... I just had an outdated version of node... I don't know why but I just started to compile everything from scratch, and now GitLab works like a charm.

So now I can say it: GitLab installation passes, if you follow @axilleas's [instructions](https://github.com/gitlabhq/gitlabhq/issues/8809#issuecomment-77275843), and if you have an up-to-date node installation (0.20.0 at the time of writing). I'm not closing the issue, I'll let you do this if you think you can!

**Comment by ZJvandeWeg** [comment] 2015-03-07 08:00
@toborrow 
What do you mean with 'works like a charm'. My page load times are very high. Have you taken special measures to combat that?

**Comment by toborrow** [comment] 2015-03-07 12:49
I mean it runs very fast and smoothly. I would say that I have a mean loading time on each page around 1sec, maximum 2.
Looking at htop while browsing gitlab, I can see that each of the 4 cpu cores stay below 5-10%.
I have approx 600 to 700mb of used RAM with GitLab (keep in mind that I also have other services running on my Pi2, like Owncloud, dovecot, postfix...). I therefore added a 1Gb swap file, but it is just in case, and did not Impact my loading times.
For PHP, I am using Nginx + PHP-FPM, using unix sockets.
And as I said, I'm using 4 workers in my GitLab config.

I think this is pretty much everything I can say about my configuration...
Have a look at it! http://gitlab.jordanbecker.fr/.

**Comment by ZJvandeWeg** [comment] 2015-03-07 12:55
Wow. Memory usage is the same here. Also have a swap file (2 GB) which is hardly used. Though when I request a simple page it takes about a minute. 
Thanks for your reply.

**Comment by toborrow** [comment] 2015-03-07 13:01
That really seems a lot! I'm surprise it doesn't timeout!...
I cannot really help you on that one... Maybe you should try to find out where the long loading time is coming from... Is your CPU used when you load a page? How many workers did you set up in gitlab config?

**Comment by ZJvandeWeg** [comment] 2015-03-07 15:54
Haven't edited that yet; as the process take all the cpu is node for some reason. But this is outside the scope of this issue I guess. 
Will google for docs on this matter later.

**Comment by axilleas** [comment] 2015-03-11 07:50
Hey guys, You can open a topic in https://forum.gitlab.com/c/arm-devices/raspberrypi and discuss further about this.

**Comment by toborrow** [comment] 2015-03-11 10:21
Will do!

**Comment by Razer6** [comment] 2015-04-01 06:53
Closing this here. There are already omnibus test packages for RPi

**Closed by Razer6** 2015-04-01 06:53 UTC

**Comment by maxlazio** [comment] 2015-04-17 07:55
You can find the Raspberry Pi 2 package for Raspbian OS [on the alternative installation page](https://about.gitlab.com/installation/). Note that it is not the latest version but we plan to update it for minor versions.
