### ISSUE TITLE
API archive problem in 8.1.0

### ISSUE THREAD

**Issue by rkgrep** [gitlabhq/gitlabhq#9763] opened 2015-10-23 07:54 UTC
Since requests are being sent through gitlab-git-http-server, a problem arised.

I try to access the archive via `api/v3/projects/namespace%2Fproject/repository/archive`. gitlab-git-http-server successfully accepts the requests and passes it to `127.0.0.1:8080`, however `%2F` is replaced to `/` and application returns 404.

````
Started GET "/api/v3/projects/rkgrep/toibiznes/repository/archive?sha=cbf1d893ecee58a2528f9822f1e58ea9db89b0f9&private_token=[FILTERED]" for 127.0.0.1 at 2015-10-23 13:52:56 +0600
Processing by NamespacesController#show as HTML
  Parameters: {"sha"=>"cbf1d893ecee58a2528f9822f1e58ea9db89b0f9", "private_token"=>"[FILTERED]", "id"=>"api/v3/projects/rkgrep/toibiznes/repository/archive"}
Completed 404 Not Found in 248ms (Views: 5.3ms | ActiveRecord: 46.6ms)
````
If I try to access `/api/v3/projects/rkgrep%2Ftoibiznes/repository/archive` without gitlab-git-http-server, it does return proper JSON.

**Comment by jacobvosmaer** [comment] 2015-10-23 12:59
Duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/3170

**Closed** 2015-10-23 13:07 UTC
