### ISSUE TITLE
Timeout and slow processing on search requests

### ISSUE THREAD

**Issue by sennav** [gitlabhq/gitlabhq#8119] opened 2014-10-21 19:42 UTC
1. **Summary**: The search request for a specific project takes too long or it timeout.
2. **Steps to reproduce**: Just select one project (gitlaburl.com/project_id) and search for something on the search box. The search from the dasboard works fine
3. **Expected behavior**:  The expected behavior is to get the search results. After the upgrade to version 7.4, the search always returned error 500. I've noticed that the unicorn worker were restarted after the request. So I increased the timeout to 120 seconds on `config/unicorn.rb`. The requests are taking 1 min to finish now. I've also noticed that in gitlab.com the requests are quite faster, so I don't know if I'm missing something on configuration files. 
4. **Observed behavior**: Timeout.
5. **Relevant logs and/or screenshots:** 
    This is the log of one request after I changed the timeout to 120 seconds:

    ```
Started GET "/search?utf8=%E2%9C%93&search=test&group_id=&project_id=28&search_code=true&repository_ref=" for 127.0.0.1 at 2014-10-21 17:12:23 -0200
Processing by SearchController#show as HTML
  Parameters: {"utf8"=>"✓", "search"=>"test", "group_id"=>"", "project_id"=>"28", "search_code"=>"true", "repository_ref"=>""}
Completed 200 OK in 75798ms (Views: 37594.5ms | ActiveRecord: 25.4ms)
Started GET "/project/notes?target_id=234&target_type=issue&last_fetched_at=1413918728" for 127.0.0.1 at 2014-10-21 17:13:28 -0200
Processing by Projects::NotesController#index as JSON
  Parameters: {"target_id"=>"234", "target_type"=>"issue", "last_fetched_at"=>"1413918728", "project_id"=>"project"}
Completed 200 OK in 29ms (Views: 0.2ms | ActiveRecord: 6.0ms)
Started POST "/api/v3/internal/allowed" for 127.0.0.1 at 2014-10-21 17:13:28 -0200
Started GET "/project/notes?target_id=234&target_type=issue&last_fetched_at=1413918728" for 127.0.0.1 at 2014-10-21 17:13:29 -0200
Processing by Projects::NotesController#index as JSON
  Parameters: {"target_id"=>"234", "target_type"=>"issue", "last_fetched_at"=>"1413918728", "project_id"=>"project"}
Completed 200 OK in 319ms (Views: 0.4ms | ActiveRecord: 19.7ms)
Started GET "/project/notes?target_id=234&target_type=issue&last_fetched_at=1413918728" for 127.0.0.1 at 2014-10-21 17:13:29 -0200
Processing by Projects::NotesController#index as JSON
  Parameters: {"target_id"=>"234", "target_type"=>"issue", "last_fetched_at"=>"1413918728", "project_id"=>"project"}
Completed 200 OK in 32ms (Views: 0.2ms | ActiveRecord: 5.9ms)
Started GET "/project/notes?target_id=234&target_type=issue&last_fetched_at=1413918728" for 127.0.0.1 at 2014-10-21 17:13:29 -0200
Processing by Projects::NotesController#index as JSON
  Parameters: {"target_id"=>"234", "target_type"=>"issue", "last_fetched_at"=>"1413918728", "project_id"=>"project"}
Completed 200 OK in 30ms (Views: 0.2ms | ActiveRecord: 5.9ms)
Started GET "/project/notes?target_id=234&target_type=issue&last_fetched_at=1413918728" for 127.0.0.1 at 2014-10-21 17:13:29 -0200
Processing by Projects::NotesController#index as JSON
  Parameters: {"target_id"=>"234", "target_type"=>"issue", "last_fetched_at"=>"1413918728", "project_id"=>"project"}
Completed 200 OK in 29ms (Views: 0.2ms | ActiveRecord: 5.7ms)
Completed 200 OK in 67899ms (Views: 36228.1ms | ActiveRecord: 23.3ms)
    ```

6. **Output of checks:**
Results of GitLab Application Check (sudo -u git -H bundle exec rake gitlab:check RAILS_ENV=production SANITIZE=true); 

    ```
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 2.0.1 ? ... OK (2.0.1)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ... 
5/25 ... ok
[...]

Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files: 
	/home/git/repositories: OK
	/home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.2.12
Send ping to redis server: PONG
gitlab-shell self-check successful

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP users with access to your GitLab server (only showing the first 100 results)
[ommited]

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ... 
5/25 ... yes
[...]

Projects have satellites? ... 
5/25 ... yes
[...]

Redis version >= 2.0.0? ... yes
Ruby version >= 2.0.0 ? ... yes (2.1.2)
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... no
  Try fixing it:
  Update your git to a version >= 1.7.10 from 1.7.9
  Please fix the error above and rerun the checks.

Checking GitLab ... Finished

    ```

    **Version of GitLab running:** SHA commit 536f61e0e77227828d363a7008bd39b0e9fd43a7

    **Setup:**
    ```
System information
System:		Ubuntu 12.04
Current User:	git
Using RVM:	no
Ruby Version:	2.1.2p95
Gem Version:	2.2.2
Bundler Version:1.7.4
Rake Version:	10.3.2
Sidekiq Version:2.17.0

GitLab information
Version:	7.4.0.rc1
Revision:	536f61e
Directory:	/home/git/gitlab
DB Adapter:	mysql2
URL:		http://gitlab
HTTP Clone URL:	http://gitlab/some-project.git
SSH Clone URL:	git@gitlab:some-project.git
Using LDAP:	yes
Using Omniauth:	no

GitLab Shell
Version:	2.0.1
Repositories:	/home/git/repositories/
Hooks:		/home/git/gitlab-shell/hooks/
Git:		/usr/bin/git

    ```

7. **Possible fixes:** I really hope that I can help you on this, but I have to get some time to learn through all your guides and code. Please let me know if this issue doesn't comply with your contributing guidelines. Thanks for all your work anyway.

**Comment by Hibbo** [comment] 2015-01-06 09:12
+1 with 7.5.3 as well.

**Comment by rsurikov** [comment] 2015-01-15 14:43
+1

**Comment by randx** [comment] 2015-01-26 16:42
Hey I cant reproduce search timeout right it now. Maybe it depends on hardware? How much RAM do you have?

**Comment by jacargentina** [comment] 2015-01-26 16:48
I have 16gb

**Comment by randx** [comment] 2015-01-26 16:55
Yeah its strange. We have working search even on VPS with 2GB RAM on repos with 10k commits

**Comment by sennav** [comment] 2015-01-26 17:15
I'm running a VPS with 1 core and 1.5GB of RAM and a VM with 2 cores and 3GB of RAM both instances with the same problem. I've been updating gitlab since version 5.4 maybe I've missed some configuration or performance parameters on those updates.

**Comment by VPusher** [comment] 2015-01-29 12:07
Same issue here with Gitlab CE 7.7.1. The search computing takes 100% CPU. I have got a 16GB (RAM) machine.


The query on a 4K commits repo (5 branches):
```
Parameters: {"project_id"=>"41", "search"=>"readme"}
Completed 200 OK in 15582ms (Views: 7716.2ms | ActiveRecord: 4.7ms)
```

**Comment by jacargentina** [comment] 2015-02-05 13:19
I'm confident: this is not about hardware but some missconfiguration.

@randx: please give me some tips on how to debug this (how can i start the app with a debugger and put a breakpoint on the search code to follow it... etc). I'm betting my head: this is about lots of unhandled errors making 100% CPU, and timeout...

**Comment by jaffacake** [comment] 2015-02-17 10:37
Updated to both 7.6.2 and 7.7.2 and still experienced this issue with both versions, we have 8GB RAM and 4 cores available.

**Comment by MatthewJWalls** [comment] 2015-02-19 13:02
Still getting this for large repositories after upgrading. Used to be fine, on 7.7.2 it now times out.

**Comment by ninjabear** [comment] 2015-04-27 16:09
+1 still on 7.10

**Comment by MatthewJWalls** [comment] 2015-04-27 16:11
We have now upgraded to 7.10 hoping that the "Improve GitLab performance when working with git repositories" would solve the issue, but it does not. The search at least returns eventually now, but on large repositories it can take a minute or more instead of the few seconds that it used to. This is on a beefy server with a large amount of memory.

**Comment by pescobar** [comment] 2015-05-13 14:40
I am also experiencing this issue in gitlab-7.9.1 when searching in big repos (it works fine for small repos)

**Comment by randx** [comment] 2015-05-14 14:56
@jacargentina you can debug it by putting `binding.pry` inside search method in rails app or in `gitlab_git` gem inself.

Search in Linux repo gives me 502 error so I can use it to reproduce problem. But from this thread I see people complaining on much smaller repos. Can someone provide a medium/small repo where they get timeout on search?

P.S. I put problem with search in huge repos to 7.12 milestone.

**Comment by MatthewJWalls** [comment] 2015-05-18 09:41
In addition to search, the history, blame etc are all much much slower than they used to be on large Repo's, and the problems with them were introduced on the 7.7.2 (approx) upgrade. Issues could be related.

**Comment by jahangiranwari** [comment] 2015-05-21 20:19
+1 with 7.10

**Comment by servomac** [comment] 2015-05-29 14:58
+1 with 7.8.1 

2015/05/29 14:26:16 [error] 1239#0: *26437 upstream prematurely closed connection while reading response header from upstream, client: 172.17.42.1, server: gitlab.domain.com, request: "GET /search?utf8=%E2%9
C%93&search=app&group_id=&project_id=4&search_code=true&repository_ref= HTTP/1.0", upstream: "http://unix:/home/git/gitlab/tmp/sockets/gitlab.socket:/search?utf8=%E2%9C%93&search=app&group_id=&project_id=4&search
_code=true&repository_ref=", host: "gitlab.domain.com"

**Comment by haisamido** [comment] 2015-05-29 15:05
+1

**Comment by servomac** [comment] 2015-05-29 15:33
I have changed the timeout value at /home/git/gitlab/config/unicorn.rb from 60 to 300 and the 502 has disappeared (but an extremly slow search is performed :p).

**Comment by artworx** [comment] 2015-06-03 07:31
Gitlab 7.10.4 here, we get many timeouts on a 5Gb repo. 

Using strace on the ruby process handling the search I see many file reads:

```
access("/home/git/repositories/test/project.git/objects/99/ef0d49d9f8042f28f5b301eff367ec4b846a96", F_OK) = 0
stat("/home/git/repositories/test/project.git/objects/99/ef0d49d9f8042f28f5b301eff367ec4b846a96", {st_mode=S_IFREG|0440, st_size=3115, ...}) = 0
open("/home/git/repositories/test/project.git/objects/99/ef0d49d9f8042f28f5b301eff367ec4b846a96", O_RDONLY|O_CLOEXEC) = 21
read(21, "x\1\355\34ko\23I\362>\363+|\354\7\7\t\274I@w+\26\220X\23 :\10Q\354\25"..., 3115) = 3115
close(21)                               = 0
```

Also I get a lot of 

```
access("/home/git/repositories/test/project.git/objects/ac/198f2cc670da3c48514d2e6de5602b4374c669", F_OK) = -1 ENOENT (No such file or directory)
access("/home/git/repositories/test/project.git/objects/ab/21fd2d66aeb6c75af431c5e8bf9ae188a35d6b", F_OK) = -1 ENOENT (No such file or directory)
```

**Comment by randx** [comment] 2015-06-03 11:24
Thank you for reports. For next release (7.12) we did some improvements to performance of GitLab but we have search performance investigation scheduled for 7.13.

**Comment by randx** [comment] 2015-07-12 12:38
Merge request with performance improvements for search code - https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/957

**Comment by sennav** [comment] 2015-07-14 14:45
Thanks @randx !

**Comment by Razer6** [comment] 2015-09-05 11:35
7.13 released, closing this

**Closed by Razer6** 2015-09-05 11:35 UTC
