### ISSUE TITLE
Preserve trailing new lines at the end of file

### ISSUE THREAD

**Issue by chulkilee** [gitlabhq/gitlabhq#9035] opened 2015-03-26 17:17 UTC
Related: #5936

- GitLab 7.9.1
- Firefox 36.0.4 on Mac

When I create or edit a text file via web editor, it removes the last new line. For example, when I put three new blank lines, only two lines are saved.

**Comment by kylekatarnls** [comment] 2015-06-30 14:12
This works well for me: #9422

**Comment by Razer6** [comment] 2015-09-05 08:21
Closing as seems to be fixed

**Closed by Razer6** 2015-09-05 08:21 UTC

**Comment by eddiemonge** [comment] 2015-09-10 23:06
This isn't fixed yet as that PR is still open. Can this stay open until then? Also fine with keeping it closed as a duplicate of #8706

**Comment by Razer6** [comment] 2015-09-11 06:48
Thanks for clarification. Then leave it closed as a duplicate of #8706 because this one was open before.
