### ISSUE TITLE
Error 500 project builds and others

### ISSUE THREAD

**Issue by boxbillinggit** [gitlabhq/gitlabhq#9928] opened 2015-12-22 15:54 UTC
```bash
NoMethodError (undefined method `gitlab_ci_project' for #<Project:0x00000006dac220>):
  app/controllers/projects/commit_controller.rb:34:in `builds'
```

**Comment by g13013** [comment] 2015-12-22 16:27
same here

**Comment by stanhu** [comment] 2015-12-23 00:31
@boxbillinggit: What version of GitLab are you running? `gitlab_ci_project` doesn't seem to exist in 8.3, only 8.1. Did you restart GitLab? If so, can you provide the full stack trace there?

@fbeegle That error shows up because the `BuildsEmailService` only exists in 8.3. @ayufan, do we need to include instructions or include a task to remove the service?

**Comment by ayufan** [comment] 2015-12-23 07:52
Yes, the 8.3 removed ci_project. @stanhu not sure what we need to remove, we run the same migrations on gitlab.com.

**Comment by stanhu** [comment] 2015-12-23 07:55
@ayufan When trying to downgrade from 8.3 to 8.2, the missing `BuildsEmailService` will cause that error mentioned above. The DB needs to be pruned of those entries.

**Comment by ayufan** [comment] 2015-12-23 07:57
@stanhu The problem is that you should do not downgrade. We reattach all CI tables to GitLab Project. So unfortunately this migration is one sided.

We should try to resolve the error for 8.3.

**Comment by g13013** [comment] 2015-12-25 11:11
@stanhu @ayufan Strange, the problem is gone, just removing the container, and re-run again!

**Comment by stanhu** [comment] 2015-12-25 17:21
Ok, I'm going to close this issue unless there are further problems to discuss.

**Closed by stanhu** 2015-12-25 17:21 UTC

**Comment by elwinar** [comment] 2016-01-09 17:49
Still getting the error…
I tried removing the container, restarting it, nothing do.
