### ISSUE TITLE
API responding to POST requests as if they're GET requests

### ISSUE THREAD

**Issue by iamsteadman** [gitlabhq/gitlabhq#10059] opened 2016-03-01 16:54 UTC
## Summary

In 8.5.1, `POST /api/v3/projects` (with a valid `name` field) returns a list of all projects in JSON with a 200 response code, therefore acting like a `GET` request.

## Steps to reproduce

Post to `/api/v3/projects` with a `name` parameter.

## Expected behaviour

I imagine the API should return either the single project just created, or an array containing just that project.

---

We've got GitLab installed on an Ubuntu DigitalOcean box. My colleague updated it a few days ago and prior to his doing so, the python-gitlab project worked fine. Since the update I ditched python-gitlab in an effort to try and figure out what had changed, so have just been using Requests. I've tried posting the data in different formats, but always get the same response.

Let me know if you need more detail.

**Comment by rymai** [comment] 2016-03-01 17:11
@iamsteadman I cannot reproduce this issue using the following CURL command:

```sh
curl -X POST -H "PRIVATE-TOKEN: [REDACTED]" -F "name=hello-world" "https://gitlab.com/api/v3/projects"
```

A new project is created and returned as JSON in the response.

**Comment by connorshea** [comment] 2016-05-25 19:27
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.

**Closed by connorshea** 2016-05-25 19:27 UTC
