### ISSUE TITLE
Avatar not handled properly using relative path in 7.5.0.rc1 

### ISSUE THREAD

**Issue by darkxinyu** [gitlabhq/gitlabhq#8366] opened 2014-11-21 01:16 UTC
I'm using relative path to serve gitlab and 7.4.2 worked well, after upgrading to 7.5.0.rc1, all my uploaded avatar has the following urls:
http://domain.com/gitlab//gitlab/uploads/user/avatar/xx/xxxxxx.jpg

**Comment by yoonyoungkim** [comment] 2015-01-21 01:19
I want to know this problem is closing in 7.6.

**Comment by Razer6** [comment] 2015-05-05 06:29
Clsong this as root cause has been reverted

**Closed by Razer6** 2015-05-05 06:29 UTC

**Comment by pierrebeitz** [comment] 2015-05-07 21:10
please reopen, as it still does not work as of 7.10.2
