### ISSUE TITLE
Filtering issues with multiple labels

### ISSUE THREAD

**Issue by roboogle** [gitlabhq/gitlabhq#8965] opened 2015-03-18 10:45 UTC
Since the labels moved from the sidebar to a dropdown menu, after the UI restructuring, it is no longer possible to select multiple labels in conjunction (i.e. with AND semantics).

This in my opinion is a dramatic downgrade, as we use group of labels to mark issues with different meaning, e.g. 

type:bug, type:feature, type:idea, type:requirement
prio:urgent
comp:c1, comp:c2, ...

So we wanted to find urgent bugs about component c2, we could filter with all the corresponding labels "type:bug, prio:urgent, comp:c2".

From the usability point of view, the labels should be brought back to the sidebar in my opinion, as selecting them is a common operation when filtering.

Furthermore, notice that github supports multiple selection of labels with AND semantics, and also support the specification of labels' names in the textual search field. 
In particular it allows to search for labels specified in the form "label:label-name" which I think would be extremely useful in gitlab as well.

I propose to restore the feature, according to this picture exemplifying the idea:

![issues-gitlab org-gitlabce](https://cloud.githubusercontent.com/assets/3163976/6706953/94927a8e-cd62-11e4-96af-1e841bc3b59b.png)

On the left sidebar, a list of all labels is show (2), to allow the users to select one or more labels to be considered in conjunction, to show only the issues that are tagged with all the selected labels. If no labels are selected, all issues are shown as the filter is not active. 

In (1) there is a filter to allow searching among labels' names. For example, writing "type:" in text entry (1) will show only labels whose name contains the string "type:", which helps when there are many defined labels.

The list can be scrolled by using scrolling bars, both horizontal and vertical (3).

The current filter which allow to select a single label (5) shall be removed, as its functionality is already contained in the new filter pane in the sidebar.

Interesting would be to able to integrate label filtering in the issues search entry, which at the moment allows for searching/filtering only on issue titles and descriptions:

![gitlab-filter](https://cloud.githubusercontent.com/assets/3163976/6707102/f63acb64-cd63-11e4-836b-ece94aa3dd5d.png)

A better integration is done e.g. by github, which allows for filtering on many topics, including labels (4):

![filters](https://cloud.githubusercontent.com/assets/3163976/6707121/1d1f0dd0-cd64-11e4-9a1d-7ca537635850.png)

Here one can search/filter by using a special syntax like <label:"label name"> as depicted in the example.

**Comment by tombamford** [comment] 2015-03-19 13:39
How about adding tickboxes to the dropdown list as it currently sits in the top bar, in a way similar to the label dropdown in Gmail for example?

**Comment by roboogle** [comment] 2015-03-19 14:05
I think a sidebar is much easier to use because:

1. There may be many labels to choose/search from, and space is larger/easier to handle
2. Sidebar can contain the searching filter, I don't know about the dropdown list
3. Easier to interact with, especially if the user selects the labels iteratively. This would require the user only to click on the desired labels, instead of looping in {open the dropdown, select one or more label, close, see the result}

However, if reintroducing the sidebar bumps against some more general/systemic design choice that led to its removal, I am not against the dropdown. Usability somehow can be sacrificed in the name of this important feature that would be reintroduced in shorter time and/or lower cost.

**Comment by roboogle** [comment] 2015-03-19 14:05
I think a sidebar is much easier to use because:

1. There may be many labels to choose/search from, and space is larger/easier to handle
2. Sidebar can contain the searching filter, I don't know about the dropdown list
3. Easier to interact with, especially if the user selects the labels iteratively. This would require the user only to click on the desired labels, instead of looping in {open the dropdown, select one or more label, close, see the result}

However, if reintroducing the sidebar bumps against some more general/systemic design choice that led to its removal, I am not against the dropdown. Usability somehow can be sacrificed in the name of this important feature that would be reintroduced in shorter time and/or lower cost.

**Comment by jkufner** [comment] 2015-04-24 09:19
The Select2 widged used for filtering is capable of handling multi-selection. No need to modify user interface significantly, just let tag select expand a little and enable the feature. Adding the list to the left menu does not seem logical to me, I don't see fit with navigation there.

**Comment by ybabel** [comment] 2015-04-25 08:07
This feature (eg. regression) is top priority for me and my team.

**Comment by DylannCordel** [comment] 2015-05-18 09:50
:+1: to use select2 and re-introduce multilabel "and" filters feature :)

**Comment by yakovkeselman** [comment] 2015-05-31 18:42
Can anyone test if the following fix works with a newer version of GitLab? https://github.com/gitlabhq/gitlabhq/pull/6350

The reason I'm asking is that I'm not running a GitLab instance myself, and GitLab.com does not have the multi-label filtering functionality.

Thanks!

**Comment by roboogle** [comment] 2015-07-28 08:15
This was implemented and waiting for MR acceptance:
https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1051

**Comment by jvanbaarsen** [comment] 2015-12-07 07:47
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Closed by jvanbaarsen** 2015-12-07 07:47 UTC
