### ISSUE TITLE
Relative link is not relative to current path, but relative to root of project

### ISSUE THREAD

**Issue by Rufflewind** [gitlabhq/gitlabhq#9613] opened 2015-09-09 09:31 UTC
Consider a repository with this structure:

    /
      /somedir
        /somedir/file1.md
        /somedir/file2.md
      /.gitignore
      /README.md

If the Markdown document `file1.md` contains a relative link like this:

    [some link](file2.md)

It doesn't work on GitLab because the link will refer to `/file1.md` in the root directory (which doesn't exist).

This behavior differs from that of GitHub and BitBucket, both of which will (correctly) resolve to `/somedir/file1.md`.

(Tested on GitLab.com in Chromium on Arch Linux x86-64)

**Comment by Rufflewind** [comment] 2015-09-09 09:50
Or never mind, it seems that the behavior changes depending on whether `/somedir/file2.md` exists or not.  If it doesn't exist then it will resolve to `/file2.md`, otherwise it will resolve to `/somedir/file2.md`.  Rather confusing, but it works.

**Comment by Rufflewind** [comment] 2015-09-10 20:41
Actually, reopening this because it's not working properly for relative paths with `../`

    /
      /somedir1
        /somedir1/file.md
      /somedir2
        /somedir2/file.md
      /.gitignore

Attempting to refer to `/somedir2/file.md` from `/somedir1/file.md` with the relative path `../somedir2/file.md` does not work.  Instead, the `../` annihilates the branch name in the URL.

**Comment by strk** [comment] 2015-10-22 17:29
Duplicate of #8855 ?

**Comment by Rufflewind** [comment] 2015-10-23 14:00
#8855 describes a different bug.

**Comment by jvanbaarsen** [comment] 2016-01-07 10:30
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Closed by jvanbaarsen** 2016-01-07 10:30 UTC
