### ISSUE TITLE
All documentation links are broken

### ISSUE THREAD

**Issue by mthibaut** [gitlabhq/gitlabhq#9644] opened 2015-09-18 19:55 UTC
Step 1. Navigate to the help directory

http://gitlab.com/help

Step 2. Click a link.

http://gitlab.com/help/permissions/doc/workflow/add-user/add-user.md

All give error 404.

This is the case in our own gitlab but also on gitlab.com.

**Comment by axilleas** [comment] 2015-09-19 08:27
I can reproduce only with the test link you provided.

**Comment by mthibaut** [comment] 2015-09-20 14:47
Interesting, the other ones do work now...

**Comment by valentingerlach** [comment] 2015-09-22 20:25
On my GitLab the link to the API Documentation is broken :/
it says: https://gitlab.example.com/help/help/api/README.md

**Comment by joseph-onsip** [comment] 2015-10-15 21:51
I just encountered this: https://gitlab.com/help/permissions/permissions.md has a broken link to https://gitlab.com/help/permissions/doc/workflow/add-user/add-user.md

**Comment by jvanbaarsen** [comment] 2016-01-07 10:32
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Closed by jvanbaarsen** 2016-01-07 10:32 UTC
