### ISSUE TITLE
Contributions calendars are empty for all users

### ISSUE THREAD

**Issue by pnull** [gitlabhq/gitlabhq#9175] opened 2015-04-23 08:49 UTC
Since we've upgraded to 7.10.0 (a651951) our contributions calendars are completely empty for all users.

However, there should be contributions.. have a look at the screenshot:
![screen shot 2015-04-23 at 10 46 14](https://cloud.githubusercontent.com/assets/872019/7293558/317de658-e9a6-11e4-8d62-e58ca19ec1c8.png)

Is there a easy way to "regenerate" contribution graph or how can i fix this?

**Comment by arif-ali** [comment] 2015-04-23 11:09
Duplicate of the issue in gitlab.com as well 

https://gitlab.com/gitlab-org/gitlab-ce/issues/1481

**Comment by Razer6** [comment] 2015-05-05 06:00
Closing as a duplicate. Fix has been merged

**Closed by Razer6** 2015-05-05 06:00 UTC

**Comment by freaz** [comment] 2015-05-16 22:22
Does it mean that fix is in version 7.10.4? Or in what version will the bugfix available? 

Thanks

**Comment by pnull** [comment] 2015-05-17 20:20
It's definitively not fixed in 7.10.4 since i'm running that version and still facing the issue.

**Comment by Razer6** [comment] 2015-05-18 08:01
This will be shipped with 7.11
