### ISSUE TITLE
dashboard not updateing

### ISSUE THREAD

**Issue by xdroff** [gitlabhq/gitlabhq#7113] opened 2014-06-11 08:53 UTC
New commits don't appear on the dashboard 

My environment:
System information
System:         Ubuntu 14.04
Current User:   git
Using RVM:      yes
RVM Version:    1.25.25
Ruby Version:   1.9.3p545
Gem Version:    2.2.2
Bundler Version:1.6.2
Rake Version:   10.3.1
Sidekiq Version:2.17.0

GitLab information
Version:        6.9.2
Revision:       e46b644
Directory:      /home/git/gitlab
DB Adapter:     mysql2
URL:            https://gitlab_url
HTTP Clone URL: https://gitlab_url/some-project.git
SSH Clone URL:  git@gitlab_url:some-project.git
Using LDAP:     no
Using Omniauth: no

GitLab Shell
Version:        1.9.4
Repositories:   /home/git/repositories/
Hooks:          /home/git/gitlab-shell/hooks/
Git:            /usr/bin/git

Checking Environment ...
Git configured for git user? ... yes
Checking Environment ... Finished
Checking GitLab Shell ...
GitLab Shell version >= 1.9.4 ? ... OK (1.9.4)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... yes
Satellites access is drwxr-x---? ... yes
update hook up-to-date? ... yes
(snip)
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: OK
Check directories and files:
        /home/git/repositories: OK
        /home/git/.ssh/authorized_keys: OK
Test redis-cli executable: redis-cli 2.8.4
Send ping to redis server: PONG
gitlab-shell self-check successful
Checking GitLab Shell ... Finished
Checking Sidekiq ...
Running? ... yes
Number of Sidekiq processes ... 1
Checking Sidekiq ... Finished
Checking LDAP ...
LDAP is disabled in config/gitlab.yml
Checking LDAP ... Finished
Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned UsersGroups? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... yes
projects have namespace: ...
(snip)
Redis version >= 2.0.0? ... yes
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.9.1)
Checking GitLab ... Finished

What shoud be done in the situation?

**Comment by zanematthew** [comment] 2015-02-27 17:47
I've noticed the same, but after running `gitlab-ctl reconfigure` sidekiq came back, but `ghost.log`, and `application.log` are still blank.

**Comment by Razer6** [comment] 2015-09-05 11:43
Duplicate of https://github.com/gitlabhq/gitlabhq/issues/7680

**Closed by Razer6** 2015-09-05 11:43 UTC
