### ISSUE TITLE
Gitlab not adding SSH keys to authorized_keys

### ISSUE THREAD

**Issue by kgoedert** [gitlabhq/gitlabhq#8629] opened 2015-01-22 11:21 UTC
Hi I am using gitlab omnibus 7.6.2 and some users add their ssh keys, they appear on the list, but a password is still requested. When I list the keys with gitlab-keys list-keys the keys are not listed.

If I use gitlab-keys add-key key-782 "ssh-rsa AAAAx321..." to add a key, it still does not work.

I also noticed that when a user tries to add a key, a process is enqueued on sidekiq and fails. But I dont see any errors on sidekiq log.

How can I fix this?

**Comment by crocket** [comment] 2015-01-28 02:05
In my case, an ssh key job is enqueued on sidekiq and stuck there forever.

**Comment by marcelkraus** [comment] 2015-01-29 21:48
I've got the same problem here with Sidekiq 2.17.8 and GitLab 7.7.1 - the jobs are enqueued and stuck there. I fixed that for now by installing Version 2.17.0, now everything works as expected.

**Comment by rumpelsepp** [comment] 2015-01-29 21:54
Did you fix your sidekiq params?
https://github.com/mperham/sidekiq/blob/master/Changes.md#2172

**Comment by marcelkraus** [comment] 2015-01-29 22:13
@rumpelsepp: Thanks a lot, but please tell me more... I am not that familiar with GitLab and Ruby. :) I checked the parameters (in "bin/background_jobs") and they look fine for me:

`sidekiq -q post_receive -q mailer -q system_hook -q project_web_hook -q gitlab_shell -q common -q default`

**Comment by rumpelsepp** [comment] 2015-01-29 22:44
I had the same problem some weeks ago caused by this particular sidekiq update. Your argument list looks good, though...

**Comment by crocket** [comment] 2015-01-30 07:03
Applying the change mentioned at https://github.com/mperham/sidekiq/blob/master/Changes.md#2172 fixed my problem.

**Comment by JaimeObregon** [comment] 2015-02-08 14:38
Same for me. After upgrading to Gitlab 7.7.2 (Sidekiq 2.17.8) from 6.9.2 a few days ago, newly added deploy keys don't work. Sidekiq's log looks good and queue names in `/bin/background_jobs` are separated by `-q`.

To have it work I had to re-add my deploy keys from the web interface while running from the shell `bundle exec sidekiq -q post_receive -q mailer -q system_hook -q project_web_hook -q gitlab_shell -q common -q default -e production`.

It worked by sheer luck ;-) as I'm not familiar with Ruby nor Sidekiq. I bet this is the cause why I'm not receiving email notifications either since I upgraded.

**Comment by Razer6** [comment] 2015-09-04 16:47
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Closed by Razer6** 2015-09-04 16:47 UTC
