### ISSUE TITLE
Gitlab unable to render images in markdown

### ISSUE THREAD

**Issue by proteus-cpi** [gitlabhq/gitlabhq#10337] opened 2016-05-15 06:36 UTC
Gitlab not able to render image files (.svg, .png) stored along with the Markdown files (README.md). In the same folder or sub-folders using relative paths (e.g. ![logo]\(doc/logo.png) \).

Gitlab version : gitlab-8.6.5-0 (bitnami stack)
Platform         : CentOS 5.7 64bit

Further accessing/downloading through the raw URL returns zero length files for image files as well!
[Possible regressin of https://github.com/gitlabhq/gitlabhq/issues/4835 which the thread indicates was fixed by https://github.com/gitlabhq/gitlabhq/commit/b883d94f969e73a55b83e142510262779f068c84)

**Comment by JisuPark** [comment] 2016-05-16 10:13
+1

**Comment by connorshea** [comment] 2016-05-17 18:04
Have you tried to do this on GitLab.com to make sure the problem is with GitLab?

**Comment by JisuPark** [comment] 2016-05-24 09:08
@connorshea Hmm.. I have similar issue under Community Edition 8.8.1.
But GitLab.com doesn't have such issues.

**Comment by connorshea** [comment] 2016-05-25 19:07
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.

**Closed by connorshea** 2016-05-25 19:07 UTC

**Comment by rleigh-codelibre** [comment] 2017-05-23 19:14
Reference: https://gitlab.com/gitlab-org/gitlab-ce/issues/17987
