### ISSUE TITLE
Projects section doesn't update starred projects count

### ISSUE THREAD

**Issue by wojtekdmyszewicz** [gitlabhq/gitlabhq#9865] opened 2015-11-26 22:05 UTC
If I star a project, the star keeps displaying zero after refreshing the page.

<img width="1007" alt="screen shot 2015-11-26 at 22 56 37" src="https://cloud.githubusercontent.com/assets/9316669/11431129/bed81438-9491-11e5-929a-7e19d9b47268.png">

**Comment by stanhu** [comment] 2015-12-02 20:25
I reproduced this too. It looks like a cache problem here:

https://github.com/gitlabhq/gitlabhq/blob/master/app/views/shared/projects/_project.html.haml#L8

Running `gitlab-rake cache:clear` refreshes the number properly.

@DouweM, what's the best way to fix this issue? We could add `stars` to the cache key, but then we'd also have to consider `avatar` and `ci` as well.

**Comment by Razer6** [comment] 2015-12-02 20:41
@stanhu I think there is a pending fix https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1939

**Comment by stanhu** [comment] 2015-12-02 21:01
Thanks, @Razer6. That works. I missed that `project` was part of the cache key. I'm also surprised that updating the star count wouldn't change the `updated_at` field.

**Comment by DouweM** [comment] 2015-12-03 09:00
Yep, will be fixed with https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1970.

**Comment by Razer6** [comment] 2015-12-03 19:33
Closing because fix merged.

**Closed by Razer6** 2015-12-03 19:33 UTC
