### ISSUE TITLE
Activity of dashboard not update

### ISSUE THREAD

**Issue by kalesastha** [gitlabhq/gitlabhq#9596] opened 2015-09-01 10:24 UTC
After updating the latest verison of gitlab 7.14.1 , merge commits are not updated on the project dashboard. But it listed in Overall dashboard.

Also debug the production.log i found the few logs it's given below for your reference ,
```
ActionView::Template::Error (No route matches {:action=>"destroy", :controller=>"projects/branches", :id=>nil, :namespace_id=>#<Group id: 455, name: "TestProject", path: "TestProject", owner_id: nil, created_at: "2014-08-07 12:07:42", updated_at: "2015-02-27 06:13:31", type: "Group", description: "Initial project", avatar: "sec.jpg">, :project_id=>#<Project id: 933, name: "cmutils", path: "cmutils", description: "", created_at: "2015-06-15 09:29:51", updated_at: "2015-09-01 07:03:37", creator_id: 455, issues_enabled: true, wall_enabled: false, merge_requests_enabled: true, wiki_enabled: true, namespace_id: 455, issues_tracker: "gitlab", issues_tracker_id: nil, snippets_enabled: false, last_activity_at: "2015-09-01 07:03:37", import_url: "", visibility_level: 10, archived: false, import_status: "none", repository_size: 57.46, star_count: 0, import_type: nil, import_source: nil, avatar: nil, commit_count: 400>} missing required keys: [:id]):
    20:               The changes were merged into
    21:               %span.label-branch= @merge_request.target_branch
    22:             You can remove the source branch now.
    23:           = link_to namespace_project_branch_path(@merge_request.source_project.namespace, @merge_request.source_project, @source_branch), remote: true, method: :delete, class: "btn btn-primary btn-sm remove_source_branch" do
    24:             %i.fa.fa-times
    25:             Remove Source Branch
    26:
  app/views/projects/merge_requests/widget/_merged.html.haml:23:in `_app_views_projects_merge_requests_widget__merged_html_haml__3861760285635147204_70303892006700'
  app/views/projects/merge_requests/widget/_show.html.haml:4:in `_app_views_projects_merge_requests_widget__show_html_haml___392674358890201902_70303891877100'
  app/controllers/projects/merge_requests_controller.rb:147:in `automerge_check'
```
Please check and let us know ....

Thanks,
Kaleeswaran N

**Comment by Razer6** [comment] 2015-09-05 11:42
Duplicate of https://github.com/gitlabhq/gitlabhq/issues/7680

**Closed by Razer6** 2015-09-05 11:42 UTC
