### ISSUE TITLE
Docs have wrong link

### ISSUE THREAD

**Issue by mathstuf** [gitlabhq/gitlabhq#8912] opened 2015-03-03 15:24 UTC
At the bottom of [the docs](http://doc.gitlab.com/ce/):

```
Generated from https///gitlab.com/gitlab-org/gitlab-ce at Tue Mar 3 14:20:18 2015, please submit improvements.
```

Note the `///` instead of `://`.

**Comment by Razer6** [comment] 2015-03-03 21:03
Closing as a duplicate of https://gitlab.com/gitlab-com/doc-gitlab-com/issues/13

**Closed by Razer6** 2015-03-03 21:03 UTC
