### ISSUE TITLE
Broken URL in long commit message shown in dashboard

### ISSUE THREAD

**Issue by renkun-ken** [gitlabhq/gitlabhq#9388] opened 2015-06-13 01:06 UTC
The URL, e.g. `https://gitlab.com/user/repo`, in a long commit message may be broken into `https://gitlab.co...` to be shown in the dashboard timeline. The URL does not direct to the right location. The correct design is, the URL text should be displayed as `https://gitlab.co...` but its `href` should be the whole URL in the commit message.

**Comment by fpgentil** [comment] 2015-06-15 01:12
Which version of Gitlab are you running? I wasn't able to reproduce here. 

![bildschirmfoto 2015-06-14 um 22 10 35](https://cloud.githubusercontent.com/assets/356881/8151375/58ff6322-12e2-11e5-93fc-5f2177cf531f.png)
![bildschirmfoto 2015-06-14 um 22 11 18](https://cloud.githubusercontent.com/assets/356881/8151376/59028e44-12e2-11e5-9229-0211ccc7e1a1.png)

**Comment by renkun-ken** [comment] 2015-06-15 01:20
I'm using gitlab.com and I mean the commit message in the dashboard (or homepage). It's like

1a2b3c4d some commit message here but cannot be fully shown [https://gitlab.co](https://gitlab.co)...

**Comment by jvanbaarsen** [comment] 2015-11-08 07:50
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Closed by jvanbaarsen** 2015-11-08 07:50 UTC
