### ISSUE TITLE
ActionView::Template::Error (undefined method `tab_width' for nil:NilClass):

### ISSUE THREAD

**Issue by cyruscavalcante** [gitlabhq/gitlabhq#9688] opened 2015-10-02 14:30 UTC
Version: GitLab 8.0.0.pre 4ac9dcc
```
Processing by ProjectsController#show as HTML
  Parameters: {"namespace_id"=>"saudeti", "id"=>"recadastramento"}
Read fragment views/19-8f7d109f7a23d3504bd122b51a96e0e3f7a34014-readme/52ae10bdb6893d3d0ad5e895fe2cc950 (0.3ms)
Completed 500 Internal Server Error in 172ms (ActiveRecord: 13.8ms)

ActionView::Template::Error (undefined method `tab_width' for nil:NilClass):
     8:             %i.fa.fa-pencil
     9:     .wiki
    10:       = cache(readme_cache_key) do
    11:         = render_readme(readme)
    12: - else
    13:   %h3.page-title
    14:     This project does not have README yet
  app/helpers/application_helper.rb:221:in `render_markup'
  app/helpers/tree_helper.rb:28:in `render_readme'
  app/views/projects/_readme.html.haml:11:in `block in _app_views_projects__readme_html_haml___2013390346559916252_70091165688280'
  app/views/projects/_readme.html.haml:10:in `_app_views_projects__readme_html_haml___2013390346559916252_70091165688280'
  app/views/projects/show.html.haml:69:in `_app_views_projects_show_html_haml__1130419082312711788_70091123525220'
  app/controllers/projects_controller.rb:85:in `block (2 levels) in show'
  app/controllers/projects_controller.rb:79:in `show'
```

**Comment by stanhu** [comment] 2015-10-03 15:57
Couple of questions:

* Is there a `README` file in your repository? Can you tell if there's something unique about it?
* Does this happen after you clear the cache (e.g. `bundle exec rake cache:clear`)
* Is this happening in GitLab 8.0.3?

**Comment by cyruscavalcante** [comment] 2015-10-03 16:34
I not had a README.MD before. The problem was fixed after creating a README.MD file in my repository.
But i think if the repository no have a readme.me could not raise a error.

**Comment by stanhu** [comment] 2015-10-03 16:40
Haven't been able to reproduce this issue. If a project doesn't have a README, I see:

![image](https://cloud.githubusercontent.com/assets/963826/10263904/bf8827ba-69b2-11e5-9a13-29b56bf8ff89.png)

Removing the README file from the repository doesn't cause an issue either.

Can you reproduce this issue? Does it happen in 8.0.3?

**Comment by cyruscavalcante** [comment] 2015-10-03 16:44
i had a README.rdoc in may repository before rename to README.md

**Comment by stanhu** [comment] 2015-10-03 16:49
README.rdoc seems to work fine for me. Renaming to README.md seems to be okay as well. I'm going to close this issue for now unless you can reproduce this issue on 8.0.3.

**Closed by stanhu** 2015-10-03 16:49 UTC
