### ISSUE TITLE
Gitlab cannot write authorized_keys

### ISSUE THREAD

**Issue by bertptrs** [gitlabhq/gitlabhq#7099] opened 2014-06-09 14:39 UTC
Whenever an authorized keys operation takes place, the logs show something like this:

	2014-06-09T14:05:58Z 2368 TID-muai0 GitlabShellWorker JID-025a63395adaf04eb5b5007d INFO: start
	/home/git/gitlab-shell/lib/gitlab_keys.rb:89:in `block in lock': uninitialized constant GitlabKeys::Timeout (NameError)
	        from /home/git/gitlab-shell/lib/gitlab_keys.rb:86:in `open'
	        from /home/git/gitlab-shell/lib/gitlab_keys.rb:86:in `lock'
	        from /home/git/gitlab-shell/lib/gitlab_keys.rb:32:in `add_key'
	        from /home/git/gitlab-shell/lib/gitlab_keys.rb:18:in `exec'
	        from /home/git/gitlab-shell//bin/gitlab-keys:21:in `<main>'

Afterwards, nothing seems to have changed.

**Comment by Razer6** [comment] 2015-05-05 06:35
Thanks for the issue report. This issue has already been fixed in newer versions of GitLab. Due to the size of this project and our limited resources we are only able to support the latest stable release as outlined in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker). In order to get this bug fix and enjoy many new features please [upgrade](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/doc/update). If you still experience issues at that time please open a new issue following our issue tracker guidelines found in the [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Closed by Razer6** 2015-05-05 06:35 UTC

**Comment by peschee** [comment] 2015-05-05 06:41
Yes, thanks. We've upgraded to the a later version and the issue is fixed.
