### ISSUE TITLE
Update from 6.0 to 7.7, showing old merge requests cause 500 errors

### ISSUE THREAD

**Issue by coconut30** [gitlabhq/gitlabhq#8732] opened 2015-02-04 08:30 UTC
Hi,

After an update of my gitlab from 6.0 to 7.7 following the doc https://github.com/gitlabhq/gitlabhq/blob/master/doc/update/6.x-or-7.x-to-7.7.md, when I try to view existing merge requests, gitlab fail to display with a 500 error. In production.log I can see that : 

Started GET "/namespace/project/merge_requests" for 127.0.0.1 at 2015-02-03 16:34:13 +0100
Processing by Projects::MergeRequestsController#index as HTML
  Parameters: {"project_id"=>"namespace/project"}
Completed 500 Internal Server Error in 56ms

ActionView::Template::Error (Invalid raw commit type: Commit):
    22:     - if merge_request.notes.any?
    23:       %span
    24:         %i.fa.fa-comments
    25:         = merge_request.mr_and_commit_notes.count
    26:     - if merge_request.milestone_id?
    27:       %span
    28:         %i.fa.fa-clock-o
  app/models/merge_request_diff.rb:68:in `new'
  app/models/merge_request_diff.rb:68:in `block in load_commits'
  app/models/merge_request_diff.rb:68:in `map'
  app/models/merge_request_diff.rb:68:in `load_commits'
  app/models/merge_request_diff.rb:50:in `commits'
  app/models/merge_request.rb:39:in `commits'
  app/models/merge_request.rb:204:in `mr_and_commit_notes'
  app/views/projects/merge_requests/_merge_request.html.haml:25:in `_app_views_projects_merge_requests__merge_request_html_haml___4251378593434022744_59353120'
  app/views/projects/merge_requests/index.html.haml:8:in `_app_views_projects_merge_requests_index_html_haml__336017911220533031_25376180'

No problem with new merge requests. If you need more info, I will be happy to post it.
Thanks

**Comment by chrislapa** [comment] 2015-02-04 22:15
I just did an upgrade from 6.0 to 7.6.2 and get something similar. The behaviour is the similar in that some merge requests show an error 500. Its weird, some old ones work and some dont. I've looked through the SQL database and can't directly see what the problem is. There is no standout difference between the working and not working ones.

My error is:
```
Started GET "/**removed**/**removed**/merge_requests/99" for 172.28.67.70 at 2015-02-03 16:45:21 +1100
Processing by Projects::MergeRequestsController#show as HTML
  Parameters: {"project_id"=>"**removed**/**removed**", "id"=>"99"}
Completed 500 Internal Server Error in 214ms

ActionView::Template::Error (undefined method `short_id' for nil:NilClass):
     8:     %div
     9:       = link_to_member(@project, note.author, avatar: false)
    10:       started a discussion on commit
    11:       = link_to(note.noteable.short_id, project_commit_path(note.project, note.noteable), class: 'monospace')
    12:     .last-update.hide.js-toggle-content
    13:       - last_note = discussion_notes.last
    14:       last updated by
  app/views/projects/notes/discussions/_commit.html.haml:11:in `_app_views_projects_notes_discussions__commit_html_haml__2845132147773347950_70011764747100'
  app/views/projects/notes/_discussion.html.haml:13:in `_app_views_projects_notes__discussion_html_haml__4139911571170084056_70011764545480'
  app/views/projects/notes/_notes.html.haml:7:in `block in _app_views_projects_notes__notes_html_haml__3180357081038837234_70011764373560'
  app/views/projects/notes/_notes.html.haml:2:in `each'
  app/views/projects/notes/_notes.html.haml:2:in `_app_views_projects_notes__notes_html_haml__3180357081038837234_70011764373560'
  app/views/projects/notes/_notes_with_form.html.haml:2:in `_app_views_projects_notes__notes_with_form_html_haml__1836016726415457532_70011764235460'
  app/views/projects/merge_requests/_show.html.haml:33:in `_app_views_projects_merge_requests__show_html_haml__1144872974554681124_70011765318520'
  app/views/projects/merge_requests/show.html.haml:1:in `_app_views_projects_merge_requests_show_html_haml__3128752638493311084_70011765271720'
  app/controllers/projects/merge_requests_controller.rb:30:in `show'
```

Did you run the migrate id's step (ruby bin/rake migrate_iids RAILS_ENV=production)?

**Comment by coconut30** [comment] 2015-02-06 15:05
Yes, I did.

**Comment by jvanbaarsen** [comment] 2015-11-07 15:43
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Closed by jvanbaarsen** 2015-11-07 15:43 UTC
