### ISSUE TITLE
Slash in branch name breaks loading commit data on Files page

### ISSUE THREAD

**Issue by aaronjwood** [gitlabhq/gitlabhq#9431] opened 2015-07-05 21:24 UTC
I have a branch named `feature/show-customer-id` and it seems to break the loading of commit data on the Files page. The message "Loading commit data..." persists since the AJAX call returns a 404. 

Here's what gets logged to the console: `GET https://<MYDOMAIN>/<USERNAME>/<PROJECT>/refs/feature%2Fshow-customer-id/logs_tree/?_=1436131362854 404 (Not Found)`

**Comment by stanhu** [comment] 2015-07-09 05:34
This may be a duplicate of GH-9257 and https://gitlab.com/gitlab-org/gitlab-ce/issues/1534. Are you using Apache or Passenger in front of GitLab? If so, you may need to use the `AllowEncodedSlashes On` option.

It seems that nginx automatically decodes encoded URLs. We need to fix GitLab not to assume the Web server will do this.

**Comment by aaronjwood** [comment] 2015-07-10 21:26
I'm using Apache in front of mine. I have this in my Apache config (taken from your docs)

```
  # Ensure that encoded slashes are not decoded but left in their encoded state.
  # http://doc.gitlab.com/ce/api/projects.html#get-single-project
  AllowEncodedSlashes NoDecode
```

**Comment by stanhu** [comment] 2015-07-11 19:22
You may want to set it to On as a workaround. Let me know if that helps.

**Comment by aaronjwood** [comment] 2015-07-11 23:37
Thanks, that certainly takes care of the issue.

**Comment by stanhu** [comment] 2015-07-12 04:18
Great. One of my to-do items is to fix GitLab so that this workaround is not necessary. For now, I'll close this.

https://gitlab.com/gitlab-org/gitlab-ce/issues/1804

**Closed by stanhu** 2015-07-12 04:18 UTC
