### ISSUE TITLE
Graphs double up

### ISSUE THREAD

**Issue by jbrooksuk** [gitlabhq/gitlabhq#7831] opened 2014-09-23 13:44 UTC
*I've only tested this bug in Chrome 38 on OSX.*

## Steps to reproduce
1. Go to the **Graphs** tab.
2. Close the Chrome tab.
3. Re-open the tab.
4. Hopefully (or not) see double.

![screen shot 2014-09-23 at 14 42 06](https://cloud.githubusercontent.com/assets/246103/4372849/b082884e-4327-11e4-8437-f440604f45ba.png)

**Comment by Razer6** [comment] 2015-02-23 22:06
It's been at least 2 weeks (and a new release) since we heard from you. I'm closing this issue but if you still experience this problem, please open a new issue (but also reference the old issue(s)). Make sure to also include the necessary debugging information conforming to the issue tracker guidelines found in our [contributing guidelines](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#issue-tracker-guidelines).

**Comment by arif-ali** [comment] 2015-02-24 01:26
I still have an issue in Firefox and Chrome, so when you re-open the tab, I get the following output; when doing it on https://gitlab.com/gitlab-org/gitlab-ce/graphs/master

```
[{"author_name":"Dmitriy Zaporozhets","author_email":"dmitriy.zaporozhets@gmail.com","date":"2015-02-23"},{"author_name":"Dmitriy Zaporozhets","author_email":"dmitriy.zaporozhets@gmail.com","date":"2015-02-23"},{"author_name":"Marin Jankovski","author_email":"marin@gitlab.com","date":"2015-02-23"},{"author_name":"Sabba Petri","author_email":"sabbap@gmail.com","date":"2015-02-23"},{"author_name":"Dmitriy Zaporozhets","author_email":"dmitriy.zaporozhets@gmail.com","date":"2015-02-23"},{"author_name":"Dmitriy Zaporozhets","author_email":"dmitriy.zaporozhets@gmail.com","date":"2015-02-23"},{"author_name":"Robert Schilling","author_email":"rschilling@student.tugraz.at","date":"2015-02-23"},{"author_name":"Robert Schilling","author_email":"rschilling@student.tugraz.at","date":"2015-02-23"},{"author_name":"Robert Schilling","author_email":"rschilling@student.tugraz.at","date":"2015-02-23"},{"author_name":"Robert Schilling","author_email":"rschilling@student.tugraz.at","date":"2015-02-23"},{"author_name":"Marco Wessel","author_email":"marco@poop.nl","date":"2015-02-23"},{"author_name":"shafan","author_email":"kepha.forum@hotmail.fr","date":"2015-02-23"},{"author_name":"Dmitriy Zaporozhets","author_email":"dmitriy.zaporozhets@gmail.com","date":"2015-02-22"},{"author_name":"Dmitriy Zaporozhets","author_email":"dmitriy.zaporozhets@gmail.com","date":"2015-02-22"},{"author_name":"Patrik Kernstock","author_email":"info@pkern.at","date":"2015-02-22"},{"author_name":"Sytse Sijbrandij","author_email":"sytse@gitlab.com","date":"2015-02-22"},{"author_name":"Dmitriy Zaporozhets","author_email":"dzaporozhets@gitlab.com","date":"2015-02-22"},{"author_name":"Dmitriy Zaporozhets","author_email":"dmitriy.zaporozhets@gmail.com","date":"2015-02-22"},{"author_name":"Vinnie Okada","author_email":"vokada@mrvinn.com","date":"2015-02-22"},{"author_name":"Robert Schilling","author_email":"rschilling@student.tugraz.at","date":"2015-02-22"},{"author_name":"Robert Schilling","author_email":"rschilling@student.tugraz.at","date":"2015-02-22"},{"author_name":"Dmitriy Zaporozhets","author_email":"dzaporozhets@gitlab.com","date":"2015-02-22"},{"author_name":"Dmitriy Zaporozhets","author_email":"dmitriy.zaporozhets@gmail.com","date":"2015-02-21"},{"author_name":"Dmitriy Zaporozhets","author_email":"dmitriy.zaporozhets@gmail.com","date":"2015-02-21"},{"author_name":"Vinnie Okada","author_email":"vokada@mrvinn.com","date":"2015-02-21"},{"author_name":"Vinnie Okada","author_email":"vokada@mrvinn.com","date":"2015-02-21"},{"author_name":"Dmitriy Zaporozhets","author_email":"dmitriy.zaporozhets@gmail.com","date":"2015-02-21"},{"author_name":"Marin Jankovski","author_email":"marin@gitlab.com","date":"2015-02-21"},{"author_name":"Douwe Maan","author_email":"douwe@gitlab.com","date":"2015-02-21"},{"author_name":"Dmitriy Zaporozhets","author_email":"dzaporozhets@gitlab.com","date":"2015-02-21"},{"author_name":"Dmitriy Zaporozhets","author_email":"dzaporozhets@gitlab.com","date":"2015-02-21"},{"author_name":"Marin Jankovski","author_email":"maxlazio@gmail.com","date":"2015-02-20"},{"author_name":"Marin Jankovski","author_email":"maxlazio@gmail.com","date":"2015-02-20"},{"author_name":"Dmitriy Zaporozhets","author_email":"dzaporozhets@gitlab.com","date":"2015-02-20"},{"author_name":"Marin Jankovski","author_email":"marin@gitlab.com","date":"2015-02-20"},{"author_name":"Douwe Maan","author_email":"douwe@gitlab.com","date":"2015-02-20"},{"author_name":"Douwe Maan","author_email":"douwe@gitlab.com","date":"2015-02-20"},{"author_name":"Douwe Maan","author_email":"douwe@gitlab.com","date":"2015-02-20"},{"author_name":"Dmitriy Zaporozhets","author_email":"dmitriy.zaporozhets@gmail.com","date":"2015-02-20"},{"author_name":"Marin Jankovski","author_email":"marin@gitlab.com","date":"2015-02-20"},{"author_name":"Dmitriy Zaporozhets","author_email":"dzaporozhets@gitlab.com","date":"2015-02-20"},{"author_name":"Douwe Maan","author_email":"douwe@gitlab.com","date":"2015-02-20"},{"author_name":"Douwe Maan","author_email":"douwe@gitlab.com","date":"2015-02-20"},{"author_name":"Dmitriy Zaporozhets","author_email":"dmitriy.zaporozhets@gmail.com","date":"2015-02-20"},{"author_name":"Marcin Kulik","author_email":"m@ku1ik.com","date":"2015-02-20"},{"author_name":"Dmitriy Zaporozhets","author_email":"dmitriy.zaporozhets@gmail.com","date":"2015-02-20"},{"author_name":"Dmitriy Zaporozhets","author_email":"dzaporozhets@gitlab.com","date":"2015-02-20"},{"author_name":"Dmitriy Zaporozhets","author_email":"dzaporozhets@gitlab.com","date":"2015-02-20"},{"author_name":"Douwe Maan","author_email":"douwe@gitlab.com","date":"2015-02-20"},{"author_name":"Douwe Maan","author_email":"douwe@gitlab.com","date":"2015-02-20"},{"author_name":"Douwe Maan","author_email":"douwe@gitlab.com","date":"2015-02-20"},{"author_name":"Douwe Maan","author_email":"douwe@gitlab.com","date":"2015-02-20"},{"author_name":"Douwe Maan","author_email":"douwe@gitlab.com","date":"2015-02-20"},{"author_name":"Douwe Maan","author_email":"douwe@gitlab.com","date":"2015-02-20"},{"author_name":"Douwe Maan","author_email":"douwe@gitlab.com","date":"2015-02-20"},{"author_name":"Douwe Maan","author_email":"douwe@gitlab.com","date":"2015-02-20"},{"author_name":"Robert Schilling","author_email":"rschilling@student.tugraz.at","date":"2015-02-20"},
```

**Comment by jvanbaarsen** [comment] 2015-11-07 20:22
I can't reproduce this issue. I guess its fixed in current version. Closing

**Closed by jvanbaarsen** 2015-11-07 20:22 UTC
Labels: Awaiting feedback, Confirmed issue
