### ISSUE TITLE
7.14.1 Issues filter, cannot clear Milestones or Label

### ISSUE THREAD

**Issue by olivierbeytrison** [gitlabhq/gitlabhq#9631] opened 2015-09-15 16:52 UTC
When filtering issues in GitLab 7.14.1 you cannot remove a previously selected milestone or label. the "Any" entry in the menu is missing

![image](https://cloud.githubusercontent.com/assets/2838126/9883534/edac7b86-5bda-11e5-9d0d-054df7ff9fa8.png)

**Comment by nicklegr** [comment] 2015-09-16 02:21
:+1:

**Comment by hliyan** [comment] 2015-09-30 18:30
Same on 8.0.0 :+1:

**Comment by stanhu** [comment] 2015-10-06 22:13
Closing since this is a duplicate of [this issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/2619). A [fix is here](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/1523).

**Closed by stanhu** 2015-10-06 22:13 UTC
