### ISSUE TITLE
Create a gitLab references to a Milestone using markdown

### ISSUE THREAD

**Issue by etiennechabert** [gitlabhq/gitlabhq#10089] opened 2016-03-16 11:17 UTC
It would be nice to be able to reference a Milestone in comments and descriptions.

We can reference lot of things (commits, issues, people and so on) the only missing reference is for Milestone which is also an important part of the workflow.

**Comment by rymai** [comment] 2016-03-16 11:42
Thanks @etiennechabert, this is a duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/13829.

**Closed by rymai** 2016-03-16 11:42 UTC
