### ISSUE TITLE
Merge request "Assign To" populating with members of the "From" repo rather than the "Target" repo

### ISSUE THREAD

**Issue by alexdiliberto** [gitlabhq/gitlabhq#5563] opened 2013-11-07 18:19 UTC
**Summary:** The Merge request "Assign To" dropdown is only populating with members of the "From" repository rather than the "Target" repository.

**Steps to reproduce:** 
1. Fork a repo
2. Code / commit / push to forked repo
3. Create a Merge Request back to the upstream repo
4. Click on the "Assign To" dropdown
5. Notice that the dropdown only contains users from the current forked repo (just myself)
6. Just go ahead and leave it blank and create the Merge Request
7. Now click edit to make changes, then click the "Assign To" dropdown again.
8. Notice now that the dropdown contains users from the target upstream repo which is different from the first time.

**Expected behavior:**
I would expect the dropdown to **always** contain users from the target upstream repo. This is actually what happens when, after I create the merge request, I click Edit and then select the "Assign To" dropdown for a second time.

**Comment by cifvts** [comment] 2015-05-19 15:12
I do not understand the state of this issue... On 7.10.4 the behavior is still showing member only of "From" repository. The Feedback page show the feature as Completed but clearly it's not: they stated "after the MR is created people can change these on the show page." which is not changing anything... I'm confused...

**Comment by sungamagnus** [comment] 2015-05-19 17:42
@cifvts I'm using 7.8.2 and it's working as intended.

In MR creation page I could select people in the `Target repository` in the `Assign to` field

**Comment by cifvts** [comment] 2015-06-15 14:26
In MR creation I can't select people in the Target repo, I can do after created the MR as Unassigned and then, after the MR has been created, I can assign to someone in the Target repo. And I think this is the expected behavior by the developers but not from the creator of this issue.

**Comment by stanhu** [comment] 2015-06-15 14:40
This should be fixed via c4e48d27a79 and released in GitLab v7.12 on June 22.

**Closed by stanhu** 2015-06-15 14:40 UTC
