### ISSUE TITLE
7.7.1 - New UI Lost Some Core Functionality

### ISSUE THREAD

**Issue by XaeroDegreaz** [gitlabhq/gitlabhq#8675] opened 2015-01-28 15:47 UTC
1. When the browser half-screen on the issue, or merge request screens, there's no way to see who is assigned to a ticket -- the drop down is missing. There's also no way to see / change the milestone.

2. For all browser sizes (eg. half / full), the link above the issue description that took you directly to the milestone page is now gone. There's no where on the page to ALWAYS see which milestone an issue / merge request is in. There is a dropdown in fullscreen, but if your milestone name is long, you have to click the dropdown in order to fully see the contents.

[There are some nice changes to the layout](https://about.gitlab.com/2015/01/16/pragmatic-redesign-for-gitlab/), but dropping critical functionality is a big step backward for my team and myself.

Half Screen (I'm assigned to the ticket, and it's in a milestone as well):
![image](https://cloud.githubusercontent.com/assets/312459/5940950/a37be072-a6d3-11e4-9878-4e453ca819e4.png)

**Comment by exabrial** [comment] 2015-01-28 15:54
Item 1: It appears maybe the responsive layout is broken. The left side collapses correctly, but the right side just goes away. This is the thing we're talking about:

![image](https://cloud.githubusercontent.com/assets/1392297/5940891/3ed5b4f4-a6d3-11e4-827e-2caaafdcabf0.png)

Item 2: If you see the above screenshot, there's no way to see the release that an issue is in without clicking the dropdown. That's a minor inconvenience, but the link to the milestone is no longer there. This makes navigation between issues and milestones very click heavy. 

Would it be possible to put a link to the milestone somewhere in this area? Thank you for consideration:

![image](https://cloud.githubusercontent.com/assets/1392297/5940955/a76def4a-a6d3-11e4-86ae-cb1ec231fc20.png)

**Comment by jasonblanchard** [comment] 2015-01-29 16:44
+1

**Comment by randx** [comment] 2015-01-29 17:01
Thank you for feedback. I will see what I can do to improve it

**Comment by jasonblanchard** [comment] 2015-01-29 17:10
I'd also say on the issue and merge request screens, that whole box with Assignee, Milestone, etc (the part that disappears on small viewports) feels very disconnected from the issue or merge request:

![screen_shot_2015-01-29_at_12 00 39_pm](https://cloud.githubusercontent.com/assets/1238532/5962123/7bfbc954-a7af-11e4-96b4-8c54dd21f2b7.png)

Maybe it's worth considering moving it back to the horizontal design between the body and the comments?

Alternatively, you could move the body over to the left and move up the Assignee and Milestone actions into the same row.

**Comment by randx** [comment] 2015-01-29 17:29
For small screens we hide a lot of controls because otherwise it turns into mess

> Maybe it's worth considering moving it back to the horizontal design between the body and the comments?

The nice thing of having controls to the right is that I can focus on content (issue title, description, comments).  For merge request it looks disconnected because of `accept merge request` widget. But I am not sure how we can improve it right now :(

**Comment by randx** [comment] 2015-01-29 17:36
Here is screenshots of issue page. Can you use it as example and give me any advices how can I improve it? 

## Desktop:

![issue-ui0screenshot](https://cloud.githubusercontent.com/assets/305940/5962604/e7aafc62-a799-11e4-8d4c-a7ac805babab.png)

## Tablet

![issue-ui0screenshot-mobile](https://cloud.githubusercontent.com/assets/305940/5962664/3f835d26-a79a-11e4-8a17-539c38c1b147.png)

**Comment by jasonblanchard** [comment] 2015-01-29 18:36
So first of all, we definitely need the assignee and milestone functionality in the tablet view. 

I also feel like that data is itself part of the content of the ticket and should be featured predominantly.

If you check out this Github ticket, the Labels, Milestone and Assignee are on the same level of the ticket text  

![screen shot 2015-01-29 at 1 32 52 pm](https://cloud.githubusercontent.com/assets/1238532/5963581/8fe9fc22-a7bb-11e4-8485-ef942929ff69.png)

I think this is the right design here.

I'm happy to work on some code for this, just haven't had any free time to get a dev environment set up :/

**Comment by rumpelsepp** [comment] 2015-01-29 18:41
> I'm happy to work on some code for this, just haven't had any free time to get a dev environment set up :/

I can point you to this one https://gitlab.com/gitlab-org/gitlab-development-kit/tree/master
It works really straight forward. If you are experienced in linux and systemd I can also point you to [systemd-nspawn](https://wiki.archlinux.org/index.php/Systemd-nspawn); I used it to make some pull requests and it worked really well.

**Comment by jasonblanchard** [comment] 2015-01-29 18:45
@rumpelsepp Thanks! I used to use the vagrant setup, but had some trouble with the Vagrantfile in the gitlab-development-kit project.

I'll probably just cave and run it on OS X.

**Comment by jasonblanchard** [comment] 2015-01-30 20:47
@randx Here's a mockup of what I mean:

![screen shot 2015-01-30 at 3 44 33 pm](https://cloud.githubusercontent.com/assets/1238532/5982997/0e1d485c-a897-11e4-879a-b9d7620adae0.png)

I think it still feels compact, but that extra issue data appears more closely related to the issue content.

I imagine it could collapse below the comments on smaller viewports to keep it available but out of the way.

**Comment by Wachiwi** [comment] 2015-01-31 09:34
+1

**Comment by fbrennen** [comment] 2015-02-02 14:13
Nice redesign -- looking good. One minor issue:

1. Using gitlab on a portrait-oriented monitor, the left nav bar is collapsed automatically to small icons. This is fine -- no objections. The problem is that there are no tooltips associated with the small icons, so the only way to tell which is which is to click on them or check the urls. It would be useful to have tooltips similar to those used in the top menu bar.

![image](https://cloud.githubusercontent.com/assets/7421357/5999257/0e575be0-aac8-11e4-95de-5c18ac32828d.png)

**Comment by sashkab** [comment] 2015-02-02 16:19
IMHO, move of the assignee and milestone to the right portion of screen, removes that width from usable space. No, instead of almost full width in 7.6, I'm getting **much** less in 7.7, so I no longer can include wide tables, etc without braking UI. 

Please re-consider and move Assignee and Milestone where they used to be, or to the description portion of the issue/merge request.

**Comment by randx** [comment] 2015-02-02 17:27
@jasonblanchard can you try the same with Merge Request page?

**Comment by jasonblanchard** [comment] 2015-02-02 17:31
@randx Yeah, I can do that.

**Comment by jasonblanchard** [comment] 2015-02-02 21:12
@randx Updated with for merge requests:

![screen shot 2015-02-02 at 1 32 55 pm](https://cloud.githubusercontent.com/assets/1238532/6009288/4aa308dc-aaf6-11e4-89b9-b010a9965f4c.png)

It behaves the same way as the issue page on smaller viewports

**Comment by sashkab** [comment] 2015-02-02 21:24
@jasonblanchard Looks better. Is it possible to use full width for the bottom portion of the MR or Issue? so Notes will get full remaining width, as it used to be in pre-7.7?

**Comment by jasonblanchard** [comment] 2015-02-02 21:30
@sashkab Thanks!

The problem with that is that will always push down the Notes below the `context` div, which under some conditions might leave a weird gap between the merge status info and the Notes.

I actually think blocks of text (like in a discussion) are easier to read when they are not full width, i.e. this github discussion page right here.

**Comment by jasonblanchard** [comment] 2015-02-02 21:35
@sashkab Also, if this https://github.com/gitlabhq/gitlabhq/pull/8697 gets merged in, that will give us more width there for viewing diffs and stuff

**Comment by sashkab** [comment] 2015-02-02 21:45
@jasonblanchard I agree, but sometimes we need to share large markdown table, and then everything brakes aka scroller added, but I have bunch of empty space for that table to fit properly. 

I agree, narrower width is easier, but for GitHub - it never was wide; with GitLab - it's been wide for awhile and in 7.7 it got changed.

**Comment by randx** [comment] 2015-02-02 21:58
@jasonblanchard the problem with your concept in MR page is that it reduces width for diffs. Especially bad for side-by-side diffs

**Comment by jasonblanchard** [comment] 2015-02-02 21:59
https://github.com/gitlabhq/gitlabhq/pull/8697 would help

**Comment by randx** [comment] 2015-02-02 22:00
if you will look through commit history for past release I first used same concept as yours. But it affected MR diffs page badly. So I changed it to what we have now.

**Comment by randx** [comment] 2015-02-02 22:02
Yes collapsed sidebar will help but: 

* I dont want to collapse-expand it everytime I go to diffs page
* On screenshot sidebar much less spacec than right column
* and you have a lot of blank space to the right which is not used. Which is especially bad fo side-by-side diffs

**Comment by randx** [comment] 2015-02-02 22:03
This problem is not so easy as it looks :smiley:

**Comment by jasonblanchard** [comment] 2015-02-02 22:03
@randx Yeah, I see what you mean.

That stuff still doesn't feel right to me tied to the "Discussion" tab, though...

Another alternative is @sashkab's suggestion of putting it back below the description.

Either way, would you accept a merge request with the existing placement but with the milestone link back in? We really need that for usability.

**Comment by jasonblanchard** [comment] 2015-02-02 22:06
The way github handles it is that context box disappears when the diff tab is active.

Want me to try that?

**Comment by randx** [comment] 2015-02-02 22:08
no because what GitHub has is actually all controls hidden under Discussion tab. WHich is almost same as it is now. If you try to apply it for your template you need to deal with blank space to right of MR title/description

**Comment by randx** [comment] 2015-02-02 22:08
or have content jumping from stretched to wide mode

**Comment by randx** [comment] 2015-02-02 22:10
This is what we can do for milestone and assignee links 

![merge request 1455 gitlab gitlabhq gitlab](https://cloud.githubusercontent.com/assets/305940/6010182/3ef2d834-aae5-11e4-963a-909c444114a9.png)

**Comment by jasonblanchard** [comment] 2015-02-02 22:11
@randx Ok thanks. I'll ditch this existing merge request and at work on getting that milestone link back.

**Comment by randx** [comment] 2015-02-02 22:33
cool thank you

**Closed** 2015-02-03 19:23 UTC
