### ISSUE TITLE
Activity feed not updating with new commits after 7.4 upgrade

### ISSUE THREAD

**Issue by robbielaw** [gitlabhq/gitlabhq#8161] opened 2014-10-24 11:16 UTC
Hey,

After we upgraded to 7.4, the activity feed (both global and local to each project) won't update to show any new commits. The commits are present as we can navigate to them through the URL.

The logs didn't seem to show anything out of the ordinary (no 500 errors etc...).

**Comment by xiaods** [comment] 2015-02-02 10:33
```bash
# cd /opt/git-data/repositories

#!/bin/bash

find . -name "hooks" -type l -delete

hooks="hooks"

for i in ./*/*.git/; do

    ln -s  /opt/gitlab/embedded/service/gitlab-shell/hooks/ $i$hooks

done
```

**Comment by palkovnik** [comment] 2015-02-13 11:42
@xiaods thanks, re-linking hooks worked for me

**Comment by UltraCoderRU** [comment] 2015-04-25 14:20
@xiaods, works for me too, thank you.

**Comment by gingaz** [comment] 2015-05-29 20:26
I've upgraded from 7.4.2 to 7.11.4 and getting similar issue. 
Commits within a period between 4 months ago and the present (right after the upgrade) is missing.
Strangely, it shows  older than 4 months commits and the ones performed after the upgrade.
Any clue?

Re-linking, hook update and clearing cache didn't help.

**Comment by gingaz** [comment] 2015-06-05 15:58
OK, mine was a different problem. 

FInaly sresolved by simply re-importing the missing projects: gitlab-rake gitlab:import:repos

**Comment by openHirn** [comment] 2015-06-06 17:33
We had symlink troubles, too (since we used CIFS based repo locations for permission reasons, however, it has been worked around and the repos are now mounted by NFS, and symlinks do work and have already been recreated like said above). However, even after restarting all services, doing some test commit and waiting some minutes (so all probably queued tasks could finish), no activity entries anywhere.

Omnibus 7.4.3 here, in a dedicated VM, working just fine in any other context.

Any further ideas on this, it is really not my favorite idea of motivating devs who have just logged in with a seemingly inactive collective. ;-/

**Comment by openHirn** [comment] 2015-06-06 21:23
Solved in our case: https://gitlab.com/gitlab-org/gitlab-ce/issues/697, ran that check until all issues were solved with one of the suggested actions and finally had the activity issue and also some others gone. In the end it was obviously both the symlink restrictions and the probably also mount- or installation-related file permission issue.

The said checking tool btw is called differently in omnibus: s/bundle exec rake/itlab-rake/
I must have somehow overlooked this helpful script in the installation guide. Mea culpa.

**Comment by maxlazio** [comment] 2015-06-08 09:01
Seems that this issue contains multiple issues and it is no longer clear what the problem is and what the solution is. If hooks were the issue after migrating from source installation to omnibus installation starting with GitLab 7.12 these will be (re)created on backup restore.

For all other issues create a new issue according to [Contributing guidelines](https://github.com/gitlabhq/gitlabhq/blob/master/CONTRIBUTING.md).

Original poster, I am going to close this issue. If your original problem is not resolved please raise a new issue with more information based on the above mentioned Contributing doc.

**Closed by maxlazio** 2015-06-08 09:01 UTC
