### ISSUE TITLE
v7.13.3 has removed all ability to manage issues

### ISSUE THREAD

**Issue by poolski** [gitlabhq/gitlabhq#9555] opened 2015-08-11 17:38 UTC
Having upgraded to v7.13.3, I've found that for some reason, despite being an administrator, I can't create and modify issues or labels on *any* projects. 

Anyone else have this problem?

**Comment by vsizov** [comment] 2015-08-12 08:16
I can't reproduce.

**Comment by poolski** [comment] 2015-08-12 09:20
It may well be something that's irrevocably screwed in my installation. I'll need to dig further.

**Comment by jvanbaarsen** [comment] 2015-12-22 07:32
Since we can't reproduce, I'm closing this issue

**Closed by jvanbaarsen** 2015-12-22 07:32 UTC
