### ISSUE TITLE
Markdown Rendering

### ISSUE THREAD

**Issue by jbrooksuk** [gitlabhq/gitlabhq#5947] opened 2013-12-29 11:21 UTC
I'm taking my Markdown issues out of #1982 as @randx has asked.

Here are my issues:

1. [https://gist.github.com/jbrooksuk/9c38e8d3f18066ebc7f0](https://gist.github.com/jbrooksuk/9c38e8d3f18066ebc7f0) As you can see: ![screen shot 2013-11-18 at 14 53 44](https://f.cloud.github.com/assets/246103/1563481/3fb85562-5061-11e3-8a1c-e4a9b9e239c5.png)
2. ![screen shot 2013-12-03 at 12 34 05](https://f.cloud.github.com/assets/246103/1663565/40f25d94-5c17-11e3-84c8-5b2e6dc1f603.png)

From what I've seen, there doesn't seem to be a pattern. For example, headings don't always work, no matter what content is **before** or **after** it. I thought it may be code blocks, but that's not an issue.

I'll add more examples tomorrow when I'm back in work.

**Comment by jbrooksuk** [comment] 2015-01-22 16:41
Still not fixed.

**Comment by Razer6** [comment] 2015-05-07 06:11
Markdown handling improved much in the last releases. Cannot reproduce these issues anymore. Closing this here for now.

**Closed by Razer6** 2015-05-07 06:11 UTC
