### ISSUE TITLE
Api unable to GET /api/v3/projects/ by project group/name

### ISSUE THREAD

**Issue by alesculek** [gitlabhq/gitlabhq#8924] opened 2015-03-06 15:08 UTC
Getting 404 when trying call this sample url: http://127.0.0.1:8080/api/v3/projects/mygroup%2Fmyproject?private_token=MY_TOKEN&sudo=1

404 is comming from apache, not gitlab's error page or error in json.
Without %2F at ID parameter is request handled by gitlab

System information
------------------------
Gitlab version from bitnami: gitlab-7.8.1-0

ales@culek:/opt/gitlab-7.8.1-0$ uname -a
Linux culek 3.13.0-46-generic #77-Ubuntu SMP Mon Mar 2 18:23:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

ales@culek:/opt/gitlab-7.8.1-0$ cat /etc/issue
Ubuntu 14.04.2 LTS \n \l

**Comment by bvamos** [comment] 2015-03-09 10:03
#8290

**Comment by NARKOZ** [comment] 2015-03-29 00:33
Duplicate of #8290

**Closed by NARKOZ** 2015-03-29 00:33 UTC
Labels: API

**Comment by GromNaN** [comment] 2015-04-01 05:25
I had a similar issue with Apache as reverse proxy.
Have you configured Apache to not rewrite entities ?

```
AllowEncodedSlashes NoDecode
```

There is an exemple on GitLab Recipes.
https://gitlab.com/gitlab-org/gitlab-recipes/commit/73abde7501b6cd128ce22ea9f82dc19fdc867c80
