### ISSUE TITLE
Replying to inline comments sometime corrupt the input form

### ISSUE THREAD

**Issue by jacob-carlborg** [gitlabhq/gitlabhq#6779] opened 2014-04-15 08:11 UTC
I don't know if "corrupt" is the best word but I've attached an image. If I click Cancel I get a new input form. If I reload the page the issue disappears. I have not been able to reproduce this issue in a reliable way.
![corrupt_discussion_form](https://cloud.githubusercontent.com/assets/306980/2704879/817aa6f2-c475-11e3-8756-a8231aca280a.png)

**Comment by Razer6** [comment] 2015-09-04 22:03
Cannot reproduce on gitlab.com on OSX with firefox. Closing for now. Report back if it still persists.

**Closed by Razer6** 2015-09-04 22:03 UTC
Labels: Awaiting feedback
