### ISSUE TITLE
First Login - Invalid Email Or Password

### ISSUE THREAD

**Issue by falsechicken** [gitlabhq/gitlabhq#7226] opened 2014-06-29 06:04 UTC
I cannot seem to log into the root account. I have tried installing several times all on a fresh Ubuntu Server 14.04 install. I followed the directions on the GitLab download page for 14.04 and it seems to work every time except when I try and log in. Ive tried three times. Twice with fresh installs on a real machine and most recently a 14.04 server VM. Every time the root login does not work. I saw another issue just like this (#3733) and it was stated that this was fixed but I am still experiencing the issue and cannot proceed any further. Thanks!

Tried using:
Username: root
Password: 5iveL!fe

Gitlab Version: 7
Ubuntu Version: 14.04 x64

**Comment by arthurfabre** [comment] 2015-01-23 18:56
This appears to still be an issue using `gitlab-7.7.0_omnibus.5.4.0.ci-1.el6.x86_64.rpm` on CentOS 6.6.
Running `gitlab-rake gitlab:setup RAILS_ENV=production` did the trick.

**Comment by jcarsique** [comment] 2015-01-28 11:31
Yet not fixed in 7.7.1 41ab9e1 (installed with `gitlab_7.7.1-omnibus.5.4.1.ci-1_amd64.deb` on Ubuntu 14.04.1).
Required `gitlab-rake gitlab:setup RAILS_ENV=production`.

**Comment by canonnervio** [comment] 2015-02-02 11:00
Yet not fixed, `gitlab_7.7.2-omnibus.5.4.2.ci-1_amd64.deb` on Debian.
Required `sudo gitlab-rake gitlab:setup RAILS_ENV=production`

**Comment by arioch** [comment] 2015-02-02 14:12
This bug and especially the lack of attention and support from Gitlab B.V to get it fixed is what's keeping me from using other products. If a bug this serious is being neglected this long I fear for my data stored in GitlabHQ. Be it enterprise or open source, I can't trust it enough to have it serve my data.

**Comment by Razer6** [comment] 2015-02-03 06:50
Since it seems appearing again, I reopen this issue. @maxlazio Can you take a look to the omnibus instal?

**Comment by maxlazio** [comment] 2015-02-03 08:03
Anyone has any logs to share? I install packages at least 10-15 times during the release cycle and never have I experienced the issue so any logs will be helpful. 
@arioch Have you supplied any logs that would help debugging this problem?

**Comment by maxlazio** [comment] 2015-02-03 08:10
@Razer6 Could you in future maybe direct this to the omnibus-gitlab issue tracker? It is impossible to follow all mentions.

**Comment by Razer6** [comment] 2015-02-03 08:13
@maxlazio Sure.

**Comment by ikuwow** [comment] 2015-02-14 14:16
same issue in 7-7-stable branch.
I installed gitlab on CentOS 6.6 by manual installation (https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/installation.md)
Does anyone have any add-hoc solutions?

**Comment by gnumoksha** [comment] 2015-03-29 01:07
the same happens with me in clean (LXC) Debian 7 installation with `gitlab_7.9.1-omnibus.1-1_amd64.deb package`. The command ` gitlab-rake gitlab:setup RAILS_ENV=production` solves the problem.

I also have two problems with `gitlab-ctl reconfigure`. The same here https://wiki.debian.org/gitlab

You wish the logs?

**Comment by lesinigo** [comment] 2015-07-16 13:15
I was hit by this problem too while playing with the vshn-gitlab Puppet module in a Vagrant VM, using gitlab-ce-7.12.2~omnibus.1-1.deb on Ubuntu Server 14.04.

Long story short, I cannot reproduce the issue with the embedded PostgreSQL database but I always hit this problem if I use an external database.

Like other have posted, it is impossible to login as root but it is possible to sign in new standard users and they log in just fine; when this happens the command `gitlab-rake gitlab:setup RAILS_ENV=production` fixes root login (possibly erasing everything else in the db, I guess).

I did some tests manually following installation instructions (no Puppet involved) and narrowed down the issue (for my specific case) to using an external PostgreSQL database. In my case I was installing a PostgreSQL on the same system as GitLab-CE, deactivating the Omnibus "internal" PostgreSQL, and configuring GitLab to connect on the database via tcp (not unix socket) on 127.0.0.1.

It works fine (GitLab actually connects to the database, creates tables, writes in them and so on) except for the root login issue.

I investigated further and found out that in both cases (embedded and external postgresql) all the tables get created and the `schema_migrations` table gets 163 rows, but only with the embedded postgresql you also get one row each in `application_settings`, `namespaces` and `users` (that's actually the root user). Additional runs of `gitlab-ctl reconfigure` do not change anything and you need to run `gitlab-rake gitlab:setup RAILS_ENV=production` to correctly get the root user in the db.

Hope this helps.

**Comment by murilodbva** [comment] 2015-08-06 13:11
Thank you @bobiblazeski it ("sudo gitlab-rake gitlab:setup RAILS_ENV=production") resolved to me.
@falsechicken , I think you should change this issue as resolved, if also resolved to you!

**Comment by appleboy** [comment] 2015-12-10 01:10
This appears to still be an issue using `gitlab-ce-8.2.2-ce.0` installed via `aptitude` on Debian 7.8 and you need run `gitlab:setup RAILS_ENV=production` to initial database table.

**Comment by andrewufrank** [comment] 2016-02-23 17:03
the issue persists with gitlab-ce_8.5.0+20160222141422-ce.1_armhf.deb
(installed on debian jessie, using an odroid - quite snappy).
the issue disappears after reboot (without using the gitlab:setup trick from above).
perhaps this helps - it is really a very annoying and probably in many cases a show stopper
thank you for otherwise a nice tool!

**Comment by vfilby** [comment] 2016-03-02 06:54
Had to do something similar when Installing the pre-canned docker image(s) on a QNAP TS-670 through Container Station.  Slightly different command since gitlab-rake wasn't in the PATH.

    root@bf7c19342eca:/home/git/gitlab# sudo -u git -H bundle exec rake gitlab:setup RAILS_ENV=production

**Comment by mlehner616** [comment] 2016-05-13 15:27
I'm experiencing this on 8.7.5 enterprise CentOS 6 Omnibus. Seeding the DB with RAILS_ENV=production makes no difference.

**Comment by mlehner616** [comment] 2016-05-13 18:38
Found the solution, nowhere in the documentation. Nothing worked until I got set the `GITLAB_ROOT_PASSWORD` inline, it appears the gitlab-rake command wasn't reading the `/etc/gitlab/gitlab.rb` as it was supposed to.

`gitlab-rake gitlab:setup RAILS_ENV=production GITLAB_ROOT_PASSWORD=somepassword GITLAB_ROOT_EMAIL=root@someplace.com`

**Comment by axilleas** [comment] 2016-05-13 19:51
On newer GitLab versions, you will be asked to set up a password on first login. Not sure what went wrong in your case.

**Comment by mlehner616** [comment] 2016-05-14 01:45
When using an external instance it seems that something in the db seed wasn't working as expected. I initially seeded the DB with the semi-documented `gitlab-rake gitlab:setup RAILS_ENV=production` (the install docs only have `gitlab-rake gitlab:setup`). It would set up the database fine except the initial user `id=1`. I could see the password reset token in the database. Then, I go to to actually login, it would ask for a new password as expected but what happens next after setting an acceptable password, it would display there were 7 errors (basically all related to username and email being empty/invalid). Obviously something went wrong because I'm never asked for either of those anywhere. When I set them explicitly during the seed as I did in my previous comments, the problem went away.

**Comment by dblessing** [comment] 2016-05-14 02:15
It looks like you're using Omnibus install. In this case you don't need to
do any database seeding. Just install, run the first reconfigure and go to
the web page.

**Comment by connorshea** [comment] 2016-05-25 19:36
Hi! We’re closing our issue tracker on GitHub so we can focus on the GitLab.com issue tracker and respond to issues faster.

If you think this is still an issue I encourage you to open it [in our issue tracker on GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce/issues). You can log in on GitLab.com using your GitHub account if you'd like to contribute an issue.

**Closed by connorshea** 2016-05-25 19:36 UTC
