### ISSUE TITLE
Backup tasks fails after upgrading

### ISSUE THREAD

**Issue by mbrgm** [gitlabhq/gitlabhq#10352] opened 2016-05-25 08:33 UTC
I upgraded to 8.8.1-ce.0 on Ubuntu Trusty; after that, the backup rake task failed:

```
rake aborted!
Errno::ENOENT: No such file or directory @ realpath_rec - /var/opt/gitlab/gitlab-rails/shared/registry
/opt/gitlab/embedded/service/gitlab-rails/lib/backup/files.rb:9:in `realpath'
/opt/gitlab/embedded/service/gitlab-rails/lib/backup/files.rb:9:in `initialize'
/opt/gitlab/embedded/service/gitlab-rails/lib/backup/registry.rb:6:in `initialize'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/backup.rake:185:in `new'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/backup.rake:185:in `block (4 levels) in <top (required)>'
/opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/backup.rake:17:in `block (3 levels) in <top (required)>'
Tasks: TOP => gitlab:backup:registry:create
(See full trace by running task with --trace)
```

The directory `/var/opt/gitlab/gitlab-rails/shared/registry` does not exist -- I guess that's the reason for the failure. After I created the directory, the backup succeeded. I see two options:

* The upgrade script should take care of creating that path.
* The backup task should check if that path exists.

**Comment by Razer6** [comment] 2016-05-25 11:03
Closing as a duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/17749

**Closed by Razer6** 2016-05-25 11:03 UTC
