### ISSUE TITLE
Close issue by commit not working anymore since 7.10.0

### ISSUE THREAD

**Issue by Soullivaneuh** [gitlabhq/gitlabhq#9300] opened 2015-05-15 13:26 UTC
If I try to commit with the following message: `Fixed #42`, commit is referenced on issue but this one is not closed anymore.

Since 7.10.0, not sure if another versions are affected.

Regards.

**Comment by mpbzh** [comment] 2015-05-15 14:39
I can confirm this on version v7.10.2, running as a docker instance (sameersbn/docker-gitlab)

**Comment by mpbzh** [comment] 2015-06-09 11:51
I could fix it. My problem was that the git hooks of my repository were not created, because the `hooks` folder within the `repository.git` folder was missing. So I created it manually and ran `sudo -u git -H /home/git/gitlab-shell/bin/create-hooks`

**Comment by Soullivaneuh** [comment] 2015-06-09 16:31
@mpbzh running your command change nothing for me. Using gitlab `7.11.4` now.

**Comment by stanhu** [comment] 2015-06-09 16:36
Are you using the omnibus version? If so, have you tried running `sudo gitlab-rake gitlab:check`? More details for source installations here:

https://github.com/gitlabhq/gitlab-public-wiki/wiki/Trouble-Shooting-Guide

**Comment by mpbzh** [comment] 2015-06-09 18:18
@Soullivaneuh run the `gitlab:check`. I had an error stating that `/path/to/repos/repo.git/hooks` did not exist. I had to go to each repository directory and create it (`mkdir hooks`), and *then* I ran the command. Then you can run `gitlab:check` again, and there should be no error anymore.

**Comment by Soullivaneuh** [comment] 2015-10-14 12:05
No output of this kind while running `gitlab:check` command, all ok.

Any new on this?

**Comment by jvanbaarsen** [comment] 2016-01-07 10:31
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Closed by jvanbaarsen** 2016-01-07 10:31 UTC
