### ISSUE TITLE
Tagged released on docker hub

### ISSUE THREAD

**Issue by drudge** [gitlabhq/gitlabhq#9582] opened 2015-08-25 18:50 UTC
Is there any interest in tagging released as they are pushed to the Docker Hub registry?

Using the `latest` tag is nice, but for people backing up and restoring, the moving target of versions is problematic. I'm happy to assist if this is a resource/time issue.

**Comment by Razer6** [comment] 2015-09-04 16:13
Duplicate of https://gitlab.com/gitlab-org/gitlab-ce/issues/2418

**Closed by Razer6** 2015-09-04 16:13 UTC
