### ISSUE TITLE
Changing an issue's milestone to "None (backlog)" removes it from "None (backlog)" filter

### ISSUE THREAD

**Issue by baldyeagle** [gitlabhq/gitlabhq#8825] opened 2015-02-19 18:09 UTC
If you change an existing issue's milestone to "None (backlog)" and try to filter by that milestone on the issue list, the reassigned issue will not appear.

I think that action sets the milestone id to null, as changing the query string of the filter list URL from "&milestone_id=0" to "&milestone_id=null" makes the issue appear.

**Comment by mtlife** [comment] 2015-02-25 15:55
Confirming this bug, I also have this problem. Same url change shows the backlog correctly. Using Gitlab 7.7.2

**Comment by rtripault** [comment] 2015-02-25 16:03
Duplicate of #8765  (and https://gitlab.com/gitlab-org/gitlab-ce/issues/1035) ?

**Closed** 2015-02-25 18:51 UTC
