### ISSUE TITLE
Gitlab-ci Integration - Merge requests

### ISSUE THREAD

**Issue by pguridi** [gitlabhq/gitlabhq#6049] opened 2014-01-14 17:06 UTC
Gitlab-ci works perfectly running builds on push. But with some merge requests I get the error "Cannot connect to CI server. Please check your setting".

The root of the problem is Gitlab CI will not build from *all* the project branches, only the selected ones from the GitlabCI UI (by default master). So, if the merge is from a branch that was never built by GitlabCI, the following line will return error:

(ci_status)
 "status = project.gitlab_ci_service.commit_status(merge_request.last_commit.sha)"

because merge_request.last_commit.sha was never built.
Merge requests between "gitlabci tracked branches" works perfectly, showing the build result in the merge view.

Would be great to have an option to track all the branches from GitlabCI

*Update: Tested in gitlab-6-4-stable and gitlabci-4-0-stable, Ubuntu 12.04 x64.

related: #4764

**Comment by brauliobo** [comment] 2015-02-21 16:45
same here, using gitlab.com and own gitlab-ci (5.4.2) with omnibus install

**Comment by brauliobo** [comment] 2015-02-21 17:05
error can be seen on https://gitlab.com/brauliobo/noosfero/merge_requests/4

**Comment by brauliobo** [comment] 2015-02-21 17:10
sorry, the problem is #7047

**Comment by Kurry** [comment] 2015-02-25 18:06
+1

**Comment by Razer6** [comment] 2015-09-04 16:20
Likely to be fixed in GitLab 8.0 in which CI and GitLab are one application.

**Closed by Razer6** 2015-09-04 16:20 UTC
