### ISSUE TITLE
When you edit your comments, the edit text box is blank (old comment not provided)

### ISSUE THREAD

**Issue by XaeroDegreaz** [gitlabhq/gitlabhq#9153] opened 2015-04-17 18:41 UTC
Just like the title says :)

GitLab 7.9.4 b10de29

**Comment by duduribeiro** [comment] 2015-04-21 05:09
Hi @XaeroDegreaz, In what screen it happened ?

I tested here on b10de29 at issues screen and worked fine =D .

Thanks

**Comment by XaeroDegreaz** [comment] 2015-05-12 14:09
@duduribeiro - Sorry for the late reply --

It happens on any screen where there is a comment. When I click to edit a comment, the comment text disappears and I have to start with a blank text box.

It's still happening on the latest release.

Before:
![image](https://cloud.githubusercontent.com/assets/312459/7589076/535591f6-f886-11e4-990c-05e0d78e2e6d.png)

After:
![image](https://cloud.githubusercontent.com/assets/312459/7589090/67308668-f886-11e4-8fb8-1110e51e9259.png)


Interestingly enough, the preview screen still shows stuff:
![image](https://cloud.githubusercontent.com/assets/312459/7589114/86b5eef6-f886-11e4-97bb-427cd28f87c5.png)

However, if I start typing into the box, the preview screen only shows my new text. If I delete everything that I typed as an "edit", the preview screen shows "Nothing to preview".

**Comment by popomore** [comment] 2015-05-25 04:58
The problem is still there, I don't know why it clones the `note-edit-form` every time I edit the comment.

**Comment by jvanbaarsen** [comment] 2015-11-08 07:47
We are currently in the process of closing down the issue tracker on GitHub, to prevent duplication with the GitLab.com issue tracker. Since this is an older issue I'll be closing this for now. If you think this is still an issue I encourage you to open it on the [GitLab.com issue tracker](https://gitlab.com/gitlab-org/gitlab-ce/issues).

**Closed by jvanbaarsen** 2015-11-08 07:47 UTC
