### ISSUE TITLE
Web UI create/delete branch actions not triggering the custom hooks (gitlab 7.5)

### ISSUE THREAD

**Issue by jkbzh** [gitlabhq/gitlabhq#8428] opened 2014-12-04 14:21 UTC
This doesn't have anything to do with the custom hooks itself, but with the trigger that invokes them when using gitlab's web  UI. Let me describe the scenario. I have a repo in gitlab and my custom hooks that do a sync to a remote puppet repo.

The following working seamlessly, working from a local clone of the repo and pushing to gitlab:
1. Creating a new branch and pushing it --> custom hooks are called and branch is synced in puppet box
2. Deleting a remote branch (e.g. git push origin :branchname) --> custom hooks are called and branch is deleted in puppet box.

However, if I do the same operations thru gitlab's web UI, the custom hooks are not called
1. Creating a new branch --> branch is created in gitlab, but the custom hooks are not called. 
2. Deleting the branch --> branch is deleted in gitlab, but the custom hooks are not called

It seems that the code that needs to trigger the hooks events is not being called. Part of that code does seem to exist because the custom hooks are called when I do edit and merge operations thru the web UI. Furthermore, if I have a branch that is already synced to my puppet repo and I do a merge operation using the UI and choose to delete it, the custom hook will be called and the branch is deleted in the remote puppet repo.

Feel free to contact me if you need further testing with this issue.

**Comment by nordicmachine** [comment] 2015-02-11 12:35
I've experienced this issue as well, but haven't looked into the code ot see if I can figure ou why the hooks aren't being triggered.

**Comment by mrts** [comment] 2015-03-01 16:48
Filed this in the official issue tracker as https://gitlab.com/gitlab-org/gitlab-ce/issues/1156

**Comment by mrts** [comment] 2015-03-24 15:04
This has been [fixed in GitLab 7.9](https://gitlab.com/gitlab-org/gitlab-ce/blob/7-9-stable/CHANGELOG#L72).

**Comment by Razer6** [comment] 2015-03-24 15:08
@mrts Thanks for bringing this up

**Closed** 2015-03-24 15:08 UTC

**Comment by nordicmachine** [comment] 2015-03-27 12:40
@mrts Have you tested that it is indeed fixed?  I'm now running Gitlab 7.9.0 and I am not getting my custom hooks to run on branch create / delete through the UI.

**Comment by mrts** [comment] 2015-03-30 13:59
Apologies, the issue is not fixed. I claimed that it is fixed due to release notes misinterpretation by people in the GitLab issue tracker, see https://gitlab.com/gitlab-org/gitlab-ce/issues/1156.
